### ISSUE TITLE
聊天室消息一多聊天界面就卡顿

### ISSUE THREAD

**Issue by XinKerrr** [tonquer/picacg-qt#100]
### 操作系统（如MacOS 10.15）
>Windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>聊天室消息一多聊天界面就卡顿

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>挂机一会聊天室

### 日志提交（问题截图或者日志，日志在logs目录）
>无

**Comment by tonquer** [comment]
可能是同时显示的消息太多了，目前设定的是1000条
