### ISSUE TITLE
MAC无法打开程序

### ISSUE THREAD

**Issue by MichaelGu718** [tonquer/picacg-qt#110]
### 操作系统（如MacOS 10.15）
>
macOS11.6

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
使用.dmg文件安装后无法打开程序

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
 移入废纸篓后重新安装也还是无法打开

### 日志提交（问题截图或者日志，日志在logs目录）
>
<img width="303" alt="截屏2021-12-23 17 59 30" src="https://user-images.githubusercontent.com/80973869/147223735-58a9313d-11be-48ed-b994-f6cfeadc85c6.png">

**Comment by tonquer** [comment]
你是Intel 还是m1

**Comment by tonquer** [comment]
> ### 操作系统（如MacOS 10.15）
> > 
> 
> macOS11.6
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > 
> 
> ### 问题描述（简要描述发生的问题）
> > 
> 
> 使用.dmg文件安装后无法打开程序
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 
> 
> 移入废纸篓后重新安装也还是无法打开
> 
> ### 日志提交（问题截图或者日志，日志在logs目录）
> > 
> 
> <img alt="截屏2021-12-23 17 59 30" width="303" src="https://user-images.githubusercontent.com/80973869/147223735-58a9313d-11be-48ed-b994-f6cfeadc85c6.png">

安装后，可能需要执行下命令才行
```
sudo xattr -r -d com.apple.quarantine /Applications/PicACG.app
```

**Comment by MichaelGu718** [comment]
> 你是Intel 还是m1

是 Intel

**Comment by MichaelGu718** [comment]
> > ### 操作系统（如MacOS 10.15）
> > > 
> > 
> > 
> > macOS11.6
> > ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > > 
> > 
> > 
> > ### 问题描述（简要描述发生的问题）
> > > 
> > 
> > 
> > 使用.dmg文件安装后无法打开程序
> > ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > > 
> > 
> > 
> > 移入废纸篓后重新安装也还是无法打开
> > ### 日志提交（问题截图或者日志，日志在logs目录）
> > > 
> > 
> > 
> > <img alt="截屏2021-12-23 17 59 30" width="303" src="https://user-images.githubusercontent.com/80973869/147223735-58a9313d-11be-48ed-b994-f6cfeadc85c6.png">
> 
> 安装后，可能需要执行下命令才行
> 
> ```
> sudo xattr -r -d com.apple.quarantine /Applications/PicACG.app
> ```

谢谢，可以了
