### ISSUE TITLE
部分漫画下载有问题

### ISSUE THREAD

**Issue by ily433664** [tonquer/picacg-qt#111]
### 操作系统（如MacOS 10.15）
> Windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>部分漫画下载有问题，查看日志貌似是路径有问题

2021-12-26 11:39:20,573 - download_info.py[line:388] - ERROR: [Errno 2] No such file or directory: 'E:/Download/bika\\commies\\楓と鈴3 (COMIC BAVEL 2019年9月号) [中国翻訳] [DL版]\\original\\汉化2 \\0001.jpg'
Traceback (most recent call last):
  File "view\download\download_info.py", line 382, in AddDownloadCompleteBack
FileNotFoundError: [Errno 2] No such file or directory: 'E:/Download/bika\\commies\\楓と鈴3 (COMIC BAVEL 2019年9月号) [中国翻訳] [DL版]\\original\\汉化2 \\0001.jpg'

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>目前下载的里面有五个漫画有这种情况，删除后下载也是这样
“楓と鈴3”是第二章有这种情况
“異世界ハーレム物語6～6.5”是第一章就这样

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/30280772/147398362-e6593b7f-7bbf-4f6b-ba8e-b01c7fc248f8.png)

**Comment by tonquer** [comment]
[已修复](https://github.com/tonquer/picacg-qt/actions/runs/1625547174)

**Comment by ily433664** [comment]
> [已修复](https://github.com/tonquer/picacg-qt/actions/runs/1625547174)

压缩文件貌似坏了，下载两次都显示文件损坏

**Comment by tonquer** [comment]
> > [已修复](https://github.com/tonquer/picacg-qt/actions/runs/1625547174)
> 
> 压缩文件貌似坏了，下载两次都显示文件损坏

我试了下载没问题，可以打开，我用Chrome浏览器下载的。

名称: bika_py37_windows_x64.zip
大小: 200170841 字节 (190 MiB)
CRC32: E37AE8BA
SHA1: 6FD122D98844B00B1FEE03B80FEC2F0D6D25C857
MD5: ac68d478266b1a044a8dccd761568091

**Comment by ily433664** [comment]
“楓と鈴3”可以正常下载了
“異世界ハーレム物語6～6.5”还是提示错误

![image](https://user-images.githubusercontent.com/30280772/147568089-5b678960-c195-45e1-b9eb-d4fd09f9383e.png)

**Comment by tonquer** [comment]
> “楓と鈴3”可以正常下载了 “異世界ハーレム物語6～6.5”还是提示错误
> 
> ![image](https://user-images.githubusercontent.com/30280772/147568089-5b678960-c195-45e1-b9eb-d4fd09f9383e.png)

你删除再下载 试试，我试了可以下载
![image](https://user-images.githubusercontent.com/22116659/147569437-173ef51d-d395-40b0-ae3d-2453711ae18e.png)

**Comment by ily433664** [comment]
下载可以了，谢谢

目前发现waifu2x转换有两个问题，waifu2x是默认设置
1、“楓と鈴3”第二章 17/25 ，转换状态显示“错误”，试了几次都是，日志显示如下
2021-12-28 22:43:07,344 - task_waifu2x.py[line:89] - WARNING: convert suc, taskId: 298, dataLen:0, sts:299 tick:0.0

2、转换有五个线程，如果任务数超过五个，前面的任务转换完也不会执行后面的，需要重新打开才能继续执行五个

**Comment by tonquer** [comment]
> 下载可以了，谢谢
> 
> 目前发现waifu2x转换有两个问题，waifu2x是默认设置 1、“楓と鈴3”第二章 17/25 ，转换状态显示“错误”，试了几次都是，日志显示如下 2021-12-28 22:43:07,344 - task_waifu2x.py[line:89] - WARNING: convert suc, taskId: 298, dataLen:0, sts:299 tick:0.0 ![image](https://user-images.githubusercontent.com/30280772/147578407-36add15e-8933-441d-bfee-39516e25cbc5.png)
> 
> 2、转换有五个线程，如果任务数超过五个，前面的任务转换完也不会执行后面的，需要重新打开才能继续执行五个

问题1是，“楓と鈴3”第二章0018.jpg这个图片是损坏的，可能是上传者弄的就是损坏的，所有waifu2x一直失败，你可以弄张好的图片替换下这个，再转换就可以了。

问题2 下载这个代码以前写的，确实有些问题，最近打算重写一下了

**Comment by ily433664** [comment]
> 问题1是，“楓と鈴3”第二章0018.jpg这个图片是损坏的，可能是上传者弄的就是损坏的，所有waifu2x一直失败，你可以弄张好的图片替换下这个，再转换就可以了。
> 
> 问题2 下载这个代码以前写的，确实有些问题，最近打算重写一下了

了解了，谢谢

**Comment by tonquer** [comment]
已更新修复转换问题
