### ISSUE TITLE
打开Waifu2x后加载不了图片

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#113]
### 操作系统（如MacOS 10.15）
>WIN10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>今日から悪い子 | 從今天起當壞孩子 打开Waifu2x后看到P40，下面的图片都不加载了，加载进度为0，退出来后看别的项目加载进度是100%，但是不显示图片，关闭Waifu2x也无法看到图片，只有关闭程序重新登陆才能恢复。关闭Waifu2x时看到P40可以看到图片。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>1.搜索“今日から悪い子 | 從今天起當壞孩子”
2.选择无邪气汉化进入，右键打开菜单把Waifu2x勾选上，下拉到P40，Bug就出现了

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/16437280/148037635-83ce0b0c-c6b1-4b6c-b391-d2c5ea1e0cc5.png)

**Comment by tonquer** [comment]
看了下是39页这个图片是有损坏的问题，waifu2x转换没有做兼容处理，
![image](https://user-images.githubusercontent.com/22116659/148069150-938c9407-820e-433e-a779-03dd70bd430b.png)

**Comment by tonquer** [comment]
> ### 操作系统（如MacOS 10.15）
> > WIN10
> 
> ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > 电信宽带
> 
> ### 问题描述（简要描述发生的问题）
> > 今日から悪い子 | 從今天起當壞孩子 打开Waifu2x后看到P40，下面的图片都不加载了，加载进度为0，退出来后看别的项目加载进度是100%，但是不显示图片，关闭Waifu2x也无法看到图片，只有关闭程序重新登陆才能恢复。关闭Waifu2x时看到P40可以看到图片。
> 
> ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > 1.搜索“今日から悪い子 | 從今天起當壞孩子”
> > 2.选择无邪气汉化进入，右键打开菜单把Waifu2x勾选上，下拉到P40，Bug就出现了
> 
> ### 日志提交（问题截图或者日志，日志在logs目录）
> > 
> 
> ![image](https://user-images.githubusercontent.com/16437280/148037635-83ce0b0c-c6b1-4b6c-b391-d2c5ea1e0cc5.png)

[1.3.3已修复](https://github.com/tonquer/picacg-qt/releases)

**Comment by mx41shy** [comment]
> > ### 操作系统（如MacOS 10.15）
> > > WIN10
> > 
> > 
> > ### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> > > 电信宽带
> > 
> > 
> > ### 问题描述（简要描述发生的问题）
> > > 今日から悪い子 | 從今天起當壞孩子 打开Waifu2x后看到P40，下面的图片都不加载了，加载进度为0，退出来后看别的项目加载进度是100%，但是不显示图片，关闭Waifu2x也无法看到图片，只有关闭程序重新登陆才能恢复。关闭Waifu2x时看到P40可以看到图片。
> > 
> > 
> > ### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> > > 1.搜索“今日から悪い子 | 從今天起當壞孩子”
> > > 2.选择无邪气汉化进入，右键打开菜单把Waifu2x勾选上，下拉到P40，Bug就出现了
> > 
> > 
> > ### 日志提交（问题截图或者日志，日志在logs目录）
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16437280/148037635-83ce0b0c-c6b1-4b6c-b391-d2c5ea1e0cc5.png)
> 
> [1.3.3已修复](https://github.com/tonquer/picacg-qt/releases)
