### ISSUE TITLE
请减少Release文件大小

### ISSUE THREAD

**Issue by liplum** [tonquer/picacg-qt#114]
### 功能描述（请清晰的、详细的描述你想要的功能）
> github上传的release压缩包太大了。内置的book.db数据库每次新版本更新几乎没有什么改变，但是每次更新都要重复下载一次。
> 压缩包内还附带了debug客户端。我建议将debug端单独打包。因为需要debug的一般是开发者，对于普通用户来说，基本下载后就删除了。

### 附加信息（其他的与功能相关的附加信息）
> 对于实现，我给出一些建议。像Entity Framework的Migration一样，每次需要更新数据库，就编写Python脚本，在第一次使用新版本时运行，进行增量式修改，而非直接发送一份完整的数据库文件的复制给用户。

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
debug可以去掉，book.db就比较麻烦了，后续改成rar压缩吧，应该能小不少
