### ISSUE TITLE
开启时自动登录

### ISSUE THREAD

**Issue by liplum** [tonquer/picacg-qt#115]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 请在开启时自动登录记忆的账号密码，并且在设置中添加开关。

### 附加信息（其他的与功能相关的附加信息）
> 因为我没有多个pic账号，所以每次登录时都不需要修改账号密码信息，并且不需要修改分流就可以正常登录。如果需要检测哪个分流可用，如果可行的话，请自动帮用户检测。

### 效果演示（可以提供可借鉴的图片）
>

**Comment by niuhuan** [comment]
可以同时保存账号密码和token, token如果超过一天就要重新获取。

**Comment by liplum** [comment]
这是有什么需要向pic的API不得不妥协的地方吗？从用户和面向视觉的角度出发，我的建议是——对用户忽略掉底层实现，用户双击程序打开后，立马就跳到首页(此时已经在后台登录完毕了，可能会有一点点延迟，加个小转轮动画即可)。

**Comment by niuhuan** [comment]
我是说把token保存在数据中，不向用户展示，第二次启动的时候走这个逻辑。官方那个token过期时间不是很懂。

**Comment by tonquer** [comment]
v1.3.4已更新支持
