### ISSUE TITLE
加入【标签+标签】的多标签分类搜索的新搜索方式

### ISSUE THREAD

**Issue by zhuixingmomo** [tonquer/picacg-qt#116]
### 希望加入【标签+标签】的多标签分类搜索的新搜索方式，可以更方便地搜索想要的内容
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 当搜索：搜索：全彩【空格】【+】纯爱，仅显示全彩且是纯爱标签的本子
当搜索：全彩【空格】【-】纯爱，显示全彩且排除纯爱标签的本子
当搜索：全彩【空格】纯爱，显示所有包含全彩、纯爱标签的本子
>

**Comment by tonquer** [comment]
如果只有分类里的标签的话，你可以用搜索界面的分类过滤去筛选

**Comment by tonquer** [comment]
v1.3.4已更新支持
