### ISSUE TITLE
Ubuntu20.04LTS下搜索结果不能正常翻页

### ISSUE THREAD

**Issue by hairenjun** [tonquer/picacg-qt#118]
### 操作系统（如MacOS 10.15）
>Ubuntu 20.04 LTS

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> VMware NAT 电信校园网，使用虚拟机运行的代理，方案为VLess+websocket+CDN

### 问题描述（简要描述发生的问题）
>无论搜索搜索结果不能翻页，点击跳转没有反应还是第一页（是刚注册的号不知道有没有影响）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 比如搜索 岛风

### 日志提交（问题截图或者日志，日志在logs目录）
>
[20220110.log](https://github.com/tonquer/picacg-qt/files/7838947/20220110.log)

**Comment by tonquer** [comment]
确实是，跳转按钮忘记绑定了。你暂时可以用滚轮滚动到最下面，会自动加载下一页

**Comment by tonquer** [comment]
v1.3.4已更新修复
