### ISSUE TITLE
win10环境下

### ISSUE THREAD

**Issue by ggtony233** [tonquer/picacg-qt#119]
### 操作系统（如MacOS 10.15）
>windows

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>梯子

### 问题描述（简要描述发生的问题）
>系统时间不准会导致登录失败，提示密码错误，但在手机上可正常登录

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>登录即可

### 日志提交（问题截图或者日志，日志在logs目录）
>直接就失败，没有日志

**Comment by tonquer** [comment]
哔咔Api里会校验请求时传入的时间

**Comment by ggtony233** [comment]
大佬有想法写个安卓平板版的吗，pica在安卓平板上面用着太蛋疼了，官方也不可能适配平行视界

**Comment by tonquer** [comment]
> 大佬有想法写个安卓平板版的吗，pica在安卓平板上面用着太蛋疼了，官方也不可能适配平行视界

安卓端可以使用这个项目
https://github.com/niuhuan/pikapika
