### ISSUE TITLE
macOS 11无法打开软件

### ISSUE THREAD

**Issue by niuhuan** [tonquer/picacg-qt#120]
### 操作系统
macOS  Big Sur (11.6)

### 网络环境
无

### 问题描述
无法打开

### 复现步骤
拖到Applications文件夹并从Launcher中打开

### 日志提交
无日志

### 截图
![QQ20220114-131828](https://user-images.githubusercontent.com/20847533/149455899-058b8989-0553-44b7-bfb1-5ef0aca4cac7.png)

**Comment by niuhuan** [comment]
感觉跟#79类似。

**Comment by tonquer** [comment]
> 类似 #79

试试 #110

**Comment by niuhuan** [comment]
可以了 @tonquer , 这个打包的时候做好呢? 如果不能的话, 要不要PIN一个issue 😊

**Comment by niuhuan** [comment]
可以了 @tonquer , 这个打包的时候做好呢? 如果不能的话, 要不要PIN一个issue 😊

**Comment by tonquer** [comment]
这个是macos限制的，没签名的软件是这样的，你从浏览器下载的话，他会修改你的文件，标识从浏览器下载的，打开就会提示文件损坏
如果是通过scp、ftp、wget之类的下载，安装打开就不会有这个提示

**Comment by niuhuan** [comment]
我也经常打包dmg上传到github, 但是没有遇到过此类问题, 命令行不知道能不能对你提供帮助。
```shell
# 清理旧的
rm -rf appimage
# 创建要打包的文件夹
mkdir appimage
# 将Applications文件将链接到appimage内
ln -sf /Applications appimage/
# 同步文件
rsync -ax build/abc.app/ appimage/abc.app/
# 打包
hdiutil create -volname abc -srcfolder appimage -ov -format UDBZ abc-v1.1.1.dmg
```
会提示用户在安全选项内允许应用的运行

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/149487302-b88e51c2-a3f9-45bf-a442-b7a0643172ce.png)
试了是一样的

**Comment by niuhuan** [comment]
这不一样, pikapika是提示安全问题, 去设置安全选项设置一下就能用了, 所有的软件网络传输后都一样, 大部分知道怎么设置。
picacg-qt是直接提示损坏, 必须命令行修复(至少我的macos 11 是这样), 还要翻看issue或查找帮助。

![1](https://user-images.githubusercontent.com/20847533/149497636-e28720b8-0e48-4ff1-95ab-2b3b519303a6.png)
![2](https://user-images.githubusercontent.com/20847533/149497653-50fb1f93-df55-4c60-bfe6-b1e3fccb5574.png)

**Comment by tonquer** [comment]
执行这个打包
```
xattr -cr dist/PicACG.app
```
测试了不会再出现已损坏提示。

**Comment by niuhuan** [comment]
可以把pin去掉，然后把这个关掉了
