### ISSUE TITLE
新增自定义字体功能

### ISSUE THREAD

**Issue by sceraser** [tonquer/picacg-qt#122]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 软件字体可自定义

### 附加信息（其他的与功能相关的附加信息）
> Windows默认字体是宋体，真的...好丑啊，希望新增自定义字体功能或将默认字体改为微软雅黑

### 效果演示（可以提供可借鉴的图片）
>Windows版的宋体字
![13b7caed2cca6276504be99a09282919](https://user-images.githubusercontent.com/42718757/151004283-af8fc389-89ad-4c9a-82a6-f54e5027135a.jpg)
相比之下Linux版的字体就好多了
![200aac3376a746c2daba27c4e0e6521f](https://user-images.githubusercontent.com/42718757/151004268-8ee1aaf7-78ec-429d-9f6a-11abaa22c68b.jpg)

**Comment by tonquer** [comment]
v1.3.5已发布，windows修改为微软雅黑

**Comment by mx41shy** [comment]
![image](https://user-images.githubusercontent.com/16437280/151834468-9b31c72c-b267-4383-b093-646572ea4100.png)
WIN11，版本1.3.5，更新后还是宋体

**Comment by tonquer** [comment]
v1.3.6设置已经支持自己设置字体
