### ISSUE TITLE
从漫画界面返回，主界面不保持全屏

### ISSUE THREAD

**Issue by ShiMi-y** [tonquer/picacg-qt#124]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>主界面全屏显示后，点击观看漫画。
从漫画中退出后，主界面会缩小，不保持全屏。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>主界面全屏显示后，点击观看漫画。
从漫画中退出后，主界面会缩小，不保持全屏。

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
设定是这样的，主界面独立设置

**Comment by ShiMi-y** [comment]
![GIF 2022-1-29 13-10-39](https://user-images.githubusercontent.com/80596204/151648362-e958b3aa-cc10-4ef9-a993-45452c0b3f51.gif)
录制了下pica和禁漫的对比

**Comment by ShiMi-y** [comment]
pica主界面全屏-看漫画-退出后主界面变成小窗看
禁漫主界面全屏-看漫画-退出后还是保持全屏

**Comment by tonquer** [comment]
v1.3.5已发布，修复了这个问题
