### ISSUE TITLE
从导航条里返回分类继续浏览时，新加载的内容非对应分区的内容

### ISSUE THREAD

**Issue by ShiMi-y** [tonquer/picacg-qt#126]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
从导航条里返回分类继续浏览时，新加载的内容非对应分区的内容

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![image](https://user-images.githubusercontent.com/80596204/151698191-845e397a-d4cc-4b45-8f6a-fe192725a04f.png)
![image](https://user-images.githubusercontent.com/80596204/151698203-75786788-1f0e-4bd6-bcfb-1078fa411912.png)

### 日志提交（问题截图或者日志，日志在logs目录）
>

**Comment by tonquer** [comment]
v1.3.5已发布，修复了这个问题
