### ISSUE TITLE
字体更换后，部分文字显示不全

### ISSUE THREAD

**Issue by ShiMi-y** [tonquer/picacg-qt#127]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![image](https://user-images.githubusercontent.com/80596204/151759902-e84abb76-9fcb-4ef8-af87-21bd2cf73344.png)
![image](https://user-images.githubusercontent.com/80596204/151759963-b239f955-7b71-48d3-8211-1d230fa2ec70.png)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
已修改
