### ISSUE TITLE
双屏时窗口边界检测有问题，鼠标在需要操作区域变成窗口缩放

### ISSUE THREAD

**Issue by heibaiqunhui** [tonquer/picacg-qt#128]
### 操作系统（如MacOS 10.15）
>Windows10 x64 企业版
2004
19041.1415

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>双屏时窗口边界检测有问题，鼠标在需要操作区域变成窗口缩放图标（上下箭头）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>当屏幕1上边缘和屏幕2不对齐时，屏幕2越靠下，可操作区域越小

i5-4590核显
屏幕1竖屏左侧（1200x1920）
屏幕2横屏右侧（1920x1080）

出问题的显示器布局：
![image](https://user-images.githubusercontent.com/43873213/152665447-1b0c64e3-377c-4b45-8285-cdc1d2cf71bd.png)
![image](https://user-images.githubusercontent.com/43873213/152665472-4677e0cc-fc3c-4a08-ba4d-d14664e8f280.png)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

https://user-images.githubusercontent.com/43873213/152665505-592980de-1d19-4814-a80a-5a9027276c27.mp4

**Comment by tonquer** [comment]
在设置中修改使用默认标题栏 可以暂时解决这个问题

**Comment by heibaiqunhui** [comment]
非常感谢，调整后功能正常了。
