### ISSUE TITLE
菜单显示不全

### ISSUE THREAD

**Issue by shibuyameltdown** [tonquer/picacg-qt#130]
### 操作系统（如MacOS 10.15）
>windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>菜单显示时被截断，只显示左半部分

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
有没有图 你指的是哪个地方

**Comment by shibuyameltdown** [comment]
> 有没有图 你指的是哪个地方

![image](https://user-images.githubusercontent.com/78797438/154096698-99fec7db-9454-4f13-9adf-b6c72e6c8ddd.png)
调窗口大小或者是全屏都会保持这样，也不是高dpi缩放的问题

**Comment by shibuyameltdown** [comment]
大佬还在吗

**Comment by tonquer** [comment]
你再设置里设置缩放100%试试

**Comment by shibuyameltdown** [comment]
设置里一直是100的，没调过

**Comment by tonquer** [comment]
暂时没发现是什么问题
我试了我的机器都正常显示

**Comment by shibuyameltdown** [comment]
会不会是win11的毛病

**Comment by tonquer** [comment]
知道问题了 是显卡名称太长了
后续修复

**Comment by shibuyameltdown** [comment]
好的感谢

**Comment by tonquer** [comment]
v1.3.6已修复
