### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by xiaoyezi-ysu** [tonquer/picacg-qt#131]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
这个怎么搞？

注册失败
( code: 400, error: 1002,message: validation error,detail": birthday must be a number of milliseconds or valid date stri
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/66401910/153824677-75d17e9f-043f-4e8a-8ad1-aeb797f2ebd4.png)

**Comment by tonquer** [comment]
注册日期 未满十八岁

**Comment by xiaoyezi-ysu** [comment]
![image](https://user-images.githubusercontent.com/66401910/153837783-14d05505-616c-466e-852f-0661c3f3a361.png)
我写的1998 够18岁了吧？

**Comment by tonquer** [comment]
奇怪了 为什么你的还会显示个周四的
正常日期是这样显示的
![image](https://user-images.githubusercontent.com/22116659/153838770-e1650e2c-c088-4705-82bc-87639b3e643a.png)

**Comment by tonquer** [comment]
你是win10哪个版本的

**Comment by xiaoyezi-ysu** [comment]
啊，那个我解决了， 以前安装的一个插件可以显示星期几，现在关了就好了
![image](https://user-images.githubusercontent.com/66401910/153839758-530712fe-845b-479e-8a8b-5a149843054f.png)
邮箱已被注册，我以前好像注册过但是密码忘了 
账号是写邮箱吗，

**Comment by tonquer** [comment]
不需要邮箱的
所以密码忘了 也没有找回功能

**Comment by xiaoyezi-ysu** [comment]
那为什么出现这个上面这个问题：email is already exist
账号和用户名不行吗

**Comment by tonquer** [comment]
这个是账号被注册了，
用户名被注册了会提示 name is already exist
