### ISSUE TITLE
win10客户端直连问题

### ISSUE THREAD

**Issue by loy4dot** [tonquer/picacg-qt#132]
### 操作系统（如MacOS 10.15）
>WIN10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>2月之前，无代理、CDN链接1.0.0.1、开启HTTPS。可以直接登录。现在会报错。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![QQ截图20220217061118](https://user-images.githubusercontent.com/20570346/154367270-63bee994-9cd7-4f9d-bd81-8be458598322.png)
![QQ截图20220217061128](https://user-images.githubusercontent.com/20570346/154367277-275f0fd5-6ca7-471d-bdd6-355bf1733f54.png)
[20220217.log](https://github.com/tonquer/picacg-qt/files/8084005/20220217.log)

**Comment by tonquer** [comment]
#48
换个CDN ip试试

**Comment by loy4dot** [comment]
谢谢，换了CDN好了
