### ISSUE TITLE
分类和搜索功能问题

### ISSUE THREAD

**Issue by shibuyameltdown** [tonquer/picacg-qt#134]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>从每个分类的某一本点进作者名字以后再退出就不能接着刚才看的那一本所在分类里的位置继续往下浏览了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
点进分类
点进本子
点进作者
返回
就会回到搜索作者页面而回不到分类页面

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
你的意思是，点击详情里的作者后，把之前的分类搜索覆盖了，而且无法返回到之前分类搜索的结果是吧

**Comment by shibuyameltdown** [comment]
对的

**Comment by tonquer** [comment]
v1.3.6已经修改
