### ISSUE TITLE
[求助] 关于登录的问题

### ISSUE THREAD

**Issue by admin-9ice** [tonquer/picacg-qt#135]
您好，我参照您的源码自己尝试实现了一下登录的部分。
目前已经能正确地获取到签名了，但仍然无法成功登录，也无法获取 authorization。

环境是 windows10 + python 3.8

下面是代码
![源码](https://user-images.githubusercontent.com/58620182/156185434-42220083-6559-43a0-b6ea-26b53f0b5d6b.png)

下面是控制台输出以及报错信息
![输出](https://user-images.githubusercontent.com/58620182/156184791-4ba8a0f0-825a-408b-a4e1-34f56adcfcba.png)

希望能收到您的解答，谢谢！

**Comment by tonquer** [comment]
如果你没有fq的话，哔咔的域名是被DNS污染的
因为DNS污染的问题，你需要将以下域名指定到对应的IP地址
104.20.180.50（对应哔咔分流2）
104.20.181.50（对应哔咔分流3）
```
  "picaapi.picacomic.com"
  "storage.wikawika.xyz",
  "storage1.picacomic.com",
  "img.tipatipa.xyz",
  "img.picacomic.com",
  "pica-pica.wikawika.xyz",
  "www.picacomic.com"
```
你可以修改系统hosts，或者用python实现自定义hosts
