### ISSUE TITLE
数据迁移bug

### ISSUE THREAD

**Issue by xmhwws** [tonquer/picacg-qt#138]
### 操作系统（如MacOS 10.15）
> win11

### 问题描述（简要描述发生的问题）
> 换电脑了,把软件文件夹和数据保存文件夹复制到新电脑,但是历史记录出错

旧电脑:

![2022-03-10_16-10-34](https://user-images.githubusercontent.com/42903751/157619024-7c69679f-00eb-416f-a019-ff83ca28b083.png)

新电脑:

<img width="959" alt="2022-03-10_16-20-06" src="https://user-images.githubusercontent.com/42903751/157619112-1f8ff26d-8966-4751-835a-416e094399a2.png">

旧电脑和新电脑的历史记录对不上,1个是15天前,1个是100+天前;1个是6页,另一个是3页;
历史记录不是保存在数据文件夹吗?直接复制粘贴没有用?

发现下载记录也对不上,老电脑47条,新电脑45条,少了2个最新下载的,但查了一下数据文件夹,却发现有这2个文件夹

**Comment by xmhwws** [comment]
1.3.5版本

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/157626897-b8ee9754-82d7-492f-aaf2-fc54fba95df6.png)
win下的记录目前是放在这的，后续考虑放到当前目录下

**Comment by xmhwws** [comment]
把.picacg文件夹复制过来,历史记录和下载记录正常了
建议把配置保存到软件文件夹下面,方便复制移动
