### ISSUE TITLE
建议下载文件的标题能加上作者名这样会方便很多

### ISSUE THREAD

**Issue by tcAllmight** [tonquer/picacg-qt#140]
现在下载的是本子本身的名字，没有作者，很不方便，这可能是网站的命名问题，要是能加上这个功能就好了，感谢！

**Comment by LyntNy4n** [comment]
我也赞同 我喜欢 [作者]标题 这样的格式

**Comment by tcAllmight** [comment]
另外我发现不带链接的描述是可以复制的，而作者名无法复制，这可能是因为作者名是带有链接的

**Comment by tonquer** [comment]
可以

**Comment by tonquer** [comment]
设置中下载一列 新增了这个设置
