### ISSUE TITLE
建议添加空格翻页功能、双页分页调整功能

### ISSUE THREAD

**Issue by Mofimg** [tonquer/picacg-qt#141]
1.空格翻页（或自定义功能按键），上下滚动无级滚动（现在为上下滑和上下翻页）
2.切换左右分页调整功能，（默认是1、2页同页，有的书封面是基数导致正文同页一直差半页，现在需要手动切换为默认后，翻一页，再重新打开左右分页才是对正的，希望可以一键调整分页）

![屏幕截图 2022-03-23 213501](https://user-images.githubusercontent.com/28688116/159712221-0eda58f3-af09-468d-a894-9d5183c677e0.png)
![屏幕截图 2022-03-23 213647](https://user-images.githubusercontent.com/28688116/159712236-64097cb9-2bcc-4b36-886a-474d32c9391b.png)

**Comment by cxhttt233** [comment]
右左双页模式，鼠标上滚才是左翻下页，希望改为鼠标下滚左翻下页

**Comment by tonquer** [comment]
上下滚动无级滚动 是什么

**Comment by tonquer** [comment]
已支持，右键菜单中或者快捷键F10会进行双页对齐
上下滚动无级滚动 现在放大后，滚轮不再是上下翻页，而是滚动到最下时才进行翻页
