### ISSUE TITLE
请问有预加载功能吗？

### ISSUE THREAD

**Issue by hongexyu122** [tonquer/picacg-qt#143]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
比如我看第一页的时候，后续的2、3、4、5、6页会预先加载好。这样不必看一页等一会儿了。
### 附加信息（其他的与功能相关的附加信息）
> 
如果可以的话，设置预加载页数，比如每次加载5页、10页、15页。
### 效果演示（可以提供可借鉴的图片）
>谢谢大佬做出这么棒的软件！

**Comment by tonquer** [comment]
有吧 目前预加载是10页

**Comment by hongexyu122** [comment]
> 有吧 目前预加载是10页

啊这，那就是我加载太慢了？请问有什么解决办法吗？vpn?

**Comment by hongexyu122** [comment]
> 有吧 目前预加载是10页

解决了，谢谢！
