### ISSUE TITLE
[提问]能具体说说哔咔聊天室websocket的机制吗

### ISSUE THREAD

**Issue by Oveln** [tonquer/picacg-qt#144]
维持心跳要给websocket发送什么消息
发送正常信息的格式又是怎么样的
看代码真的看的头晕了抱歉（

**Comment by tonquer** [comment]
#23

**Comment by tonquer** [comment]
发送消息格式请看，chat_room_widget.py里的SendMsg函数

**Comment by Oveln** [comment]
那，悄悄话呢，为什么被悄悄话websocket没有收到信息

**Comment by Oveln** [comment]
哦哦，我没有init
