### ISSUE TITLE
部分页面爱心显示错误

### ISSUE THREAD

**Issue by tcAllmight** [tonquer/picacg-qt#146]
分类-最新更新。存在很多列表页面爱心和详情页面不匹配的情况，而且还有很多0，其他分区也有这种情况，但比较少。软件是最新版本。排行榜正常但也偶尔有显示错误的情况。还有少部分是列表爱心显示正常，详情页显示异常。

**Comment by tonquer** [comment]
这和本软件搜索实现的方式有关，
搜索是用的本地搜索，并没有用哔咔API，
只保证章节数一致，其他不保证和哔咔一致

**Comment by tonquer** [comment]
爱心数只能版本更新时，同步一次最新的，后面不能实时同步
