### ISSUE TITLE
mac端标签与分类显示不全

### ISSUE THREAD

**Issue by flappybriefs** [tonquer/picacg-qt#153]
### 操作系统（如MacOS 10.15）
> macOS 12.4 beta2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 网络正常

### 问题描述（简要描述发生的问题）
> mac端绝大部分标签与分类显示不全

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 打开就是这样的

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
> 
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/35480800/164141762-76cfae90-7ffb-47f0-bae9-359e80fa290f.png">

**Comment by tonquer** [comment]
v1.3.7更新已支持
