### ISSUE TITLE
在看有几百页的图集时只能获取到前40或前80页

### ISSUE THREAD

**Issue by misaka15565** [tonquer/picacg-qt#156]
### 操作系统（如MacOS 10.15）
>Windows 10 19044.1645

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带，有代理

### 问题描述（简要描述发生的问题）
>在看有几百页的图集时只能获取到前40或前80页

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>搜索alpha，打开“[Fanbox] Alpha CG集 无码”，点击第一话或者第二话，只有前40页

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20220424.log](https://github.com/tonquer/picacg-qt/files/8547661/20220424.log)

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/166097414-100da5ed-89fe-4858-b8cb-607689ea6395.png)
日志里显示是请求太频繁的问题

**Comment by tonquer** [comment]
v1.3.7尝试修复了，可以试试
