### ISSUE TITLE
picacg翻墙还是打不开，大佬救命

### ISSUE THREAD

**Issue by sdiuhfb** [tonquer/picacg-qt#157]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>翻墙了还是显示进不去，显示错误

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![屏幕截图 2022-04-24 233758](https://user-images.githubusercontent.com/104314692/164984312-f4632a39-fb7d-42ba-a066-4d457ef3b19e.png)

**Comment by tonquer** [comment]
这个是bika返回的提示，意思是账号或密码错误
