### ISSUE TITLE
使用v2rayN(Windows版)如何使用哔咔

### ISSUE THREAD

**Issue by Hynog** [tonquer/picacg-qt#158]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动卡的手机热点

### 问题描述（简要描述发生的问题）
>用v2rayN时，哔咔代理界面如何设置

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>在v2rayN正在使用代理服务器的时候，打开哔咔，但显示"无网络链接，请检查代理“，后续操作如下：
1、对该哔咔的代理进行设置，选择**http**代理，地址填v2rayN中一个能链接到的服务器地址(不是订阅地址)
**启用https**，选择“**分流2**”，依然是"无网络链接，请检查代理设置“
2、将v2rayN打开哔咔选择无代理，启用**https**，分流2，无效

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
v2rayN不是手机的吗

**Comment by tonquer** [comment]
选择http代理或者sock5代理，地址填v2rayN上面提供的代理地址
![image](https://user-images.githubusercontent.com/22116659/165742151-281e9f29-8dfd-4522-a0d1-b70639ef45c6.png)

**Comment by Hynog** [comment]
请问这个地址在应该怎么看到(我这图片上传不了)，我是在v2rayN上有三个订阅，其中有上百个服务器，前五个栏目为类型、别名、地址、端口、加密方式，比如我当前链接的这个服务器这5个项目分别为(Vmess\cn_中国_YouTube:VV科技_23\in01.ns2333.xyz\63088\auto)，我填在哔咔上的就是这里的地址"in01.ns2333.xyz"，但无法连接(显示无网络连接)，但其它应用可以正常访问被限制的网址，比如谷歌搜索、pixiv等

PS：我后台长期挂着stem++(用来加速GitHub的)

**Comment by Hynog** [comment]
没事了，我看到了，http地址在应用的最下面

**Comment by Hynog** [comment]
老哥，我这试了取消启动https，代理的延迟出现了信息，但数据哪仍是fail(即：299ms/fail)，请问下这该怎么解决？(三个分流代理都是这样，有延迟但没数据，但分流3反过来有数据没延迟)

**Comment by tonquer** [comment]
取消https不一定能用，因为哔咔部分接口强制跳转了https

**Comment by tonquer** [comment]
可能是你的v2ray的有些哔咔的域名直连了，用全局模式，或者自定义PAC，以下域名要走代理
picaapi.picacomic.com
s3.picacomic.com
storage1.picacomic.com
img.tipatipa.xyz
img.picacomic.com
www.picacomic.com
storage-b.picacomic.com

**Comment by Hynog** [comment]
解决了，我换了一个延迟高一点的服务器成功了，对了我之前用的是PAC模式(开启PAC,并自动配置系统代理)，当时测速时返回的只有延迟数据没网速数据(显示fail)
