### ISSUE TITLE
软件内显示章节加载失败

### ISSUE THREAD

**Issue by Ralph0819** [tonquer/picacg-qt#159]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
代理用的v2rayN，然后在http代理栏里面填写的v2rayn的代理ip，在对各分流测速时都能ping通，但是在阅读漫画时显示章节加载失败，且除了搜索能用，其他栏目（首页、留言板、分类等）均为空白页面。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![image](https://user-images.githubusercontent.com/104663265/166088604-e463e312-8bba-4b96-a3bf-d35ae9e9bd34.png)
![image](https://user-images.githubusercontent.com/104663265/166088610-d3386a86-5309-4914-b9bc-4fc84276a6d5.png)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20220430.log](https://github.com/tonquer/picacg-qt/files/8595571/20220430.log)

**Comment by tonquer** [comment]
你没有登录成功吗

**Comment by tonquer** [comment]
v1.3.7尝试修复了，可以试试
