### ISSUE TITLE
无法登陆，报“未知错误”

### ISSUE THREAD

**Issue by asuo123** [tonquer/picacg-qt#161]
### 操作系统（如MacOS 10.15）
>Windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）

![Snipaste_2022-05-03_18-08-09](https://user-images.githubusercontent.com/103419084/166442496-e78d9eca-6970-4f22-937b-9121422b69a8.png)
![Snipaste_2022-05-03_18-09-19](https://user-images.githubusercontent.com/103419084/166442625-95c97464-bc93-468f-9b60-7e7db23740fb.png)
如上图所示，无法登陆或联网

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>试了多个分流，还是不行

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
[20220503.log](https://github.com/tonquer/picacg-qt/files/8610054/20220503.log)
这是日志文件，可以下载后查看，谢谢大佬

**Comment by tonquer** [comment]
这是你的IP触发了Couldfare的防火墙了
因为我没出现过，所以不好去解决这个问题，
最好的方式就是找个代理

![image](https://user-images.githubusercontent.com/22116659/166445363-75c001e5-1517-454e-a91c-8763d5e386cd.png)

**Comment by asuo123** [comment]
@tonquer 谢谢你，同志，我还是找个代理罢
