### ISSUE TITLE
阅读模式右左双页模式下，鼠标滚轮上滚是下一页

### ISSUE THREAD

**Issue by cxhttt233** [tonquer/picacg-qt#162]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
感觉这样有点违反逻辑和直觉，一般滚轮下滚才是下一页吧

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
目前左右和右左操作都是反的，后续把操作反向单独设置吧

**Comment by tonquer** [comment]
v1.3.8新增了，你可以使用这个
![image](https://user-images.githubusercontent.com/22116659/175799529-6c1a7db9-4cd8-4979-aeb5-ae95746d3ad4.png)
