### ISSUE TITLE
一个登录问题

### ISSUE THREAD

**Issue by DarthMikuH** [tonquer/picacg-qt#163]
MacOS 10.15
>
<img width="1440" alt="截屏2022-05-05 上午8 17 28" src="https://user-images.githubusercontent.com/62818311/166847208-1b5dc2d1-deeb-40b9-85e1-6c511b61e5b5.png">

### 网络环境（电信宽带）
>

### 问题描述（简要描述发生的问题）
>
如图

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>登录即可

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by DarthMikuH** [comment]
查证了，是官方的问题

**Comment by tonquer** [comment]
这是couldfare的5秒盾，防ddos的。后续看做个小工具解决这个问题
