### ISSUE TITLE
收藏内同一项目复数出现

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#164]
### 操作系统（如MacOS 10.15）
>WIN7&WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>收藏内同一项目复数出现
补充：后面在使用时，发现取消收藏后重新收藏，则重复收藏项目就会合并消失。按创建时间排序以外时项目复数出现，如果我有80页收藏，那重复会占掉一部分的页数，但是80页以后的收藏看不到。按创建时间排序时，如果最后一页项目不满一页则使用第一页的项目充满。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>用着用着就出现了，只修改过封面大小，下载缓存格式，和看图是否使用waifu2x这些项目。
除了按创建时间排序稍微正常一点，其他排序方式都不正常（排序结果不正确），而且还会出现项目重复问题，用的时间越久，项目重复次数越多。但是收藏栏内“更新完成”标签处显示“错误”时，会出现按新旧排序，此时排序无误。

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![167285204-a86dbcbc-4054-4d24-8545-02fb9b0a239c_edit_1835402294797540](https://user-images.githubusercontent.com/16437280/167729674-740fed80-e3ce-49fc-9cc2-a42694d9f994.png)

**Comment by mx41shy** [comment]
补充：后面在使用时，发现取消收藏后重新收藏，则重复收藏项目就会合并消失。

**Comment by tonquer** [comment]
v1.3.8已修复
