### ISSUE TITLE
那个dalao能出一期使用教程吗？

### ISSUE THREAD

**Issue by g2281907225** [tonquer/picacg-qt#165]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
HTTP代理和Sock5代理，CND的代理地址，这都啥啊?dalao能解释一下着都是什么东西吗？是真的不知道咋填，网上也没有相应的教程学习
### 附加信息（其他的与功能相关的附加信息）
> 使用软件为：picACG

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
有空我整理一下

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/discussions/48
