### ISSUE TITLE
发现有部分上传者的上传内容看不了呢

### ISSUE THREAD

**Issue by tuanbabann** [tonquer/picacg-qt#169]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
排行榜裡面的上傳者，點擊他有的會出現他上傳的內容，有的則不然

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 

- [ ] #176

**Comment by tonquer** [comment]
v1.3.8已修复
