### ISSUE TITLE
对话框按钮重叠

### ISSUE THREAD

**Issue by zhiyiYo** [tonquer/picacg-qt#172]
### 操作系统（如MacOS 10.15）
> Win11 22621

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 移动带宽

### 问题描述（简要描述发生的问题）
> 对话框上的标签页按钮重叠
![image](https://user-images.githubusercontent.com/65096819/171982622-b4c83bca-bf04-47de-b1fd-6a2aa1122298.png)

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 重复点击标签页按钮就会出现该情况

**Comment by tonquer** [comment]
v1.3.8已修复
