### ISSUE TITLE
希望离线状态也可以查看自己收藏并下载到本地的本子

### ISSUE THREAD

**Issue by Dylan001130** [tonquer/picacg-qt#173]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
因为下载到本子的本子都是多个文件夹嵌套，而且都是图片形式，各种漫画图片查看软件都不太好处理。所以希望离线状态也可以查看自己收藏并下载到本地的本子
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
v1.3.9已经支持
