### ISSUE TITLE
登录问题（直接代理BaseURL后出现的问题）

### ISSUE THREAD

**Issue by MomentQYC** [tonquer/picacg-qt#177]
### 操作系统（如MacOS 10.15）
>Windows 11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动但是代理

### 问题描述（简要描述发生的问题）
>登录显示一闪而过的
```
{
  "code": 400,
  "error": "1001",
  "message": "the format of accept header is invalid"
}
```

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>登录

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>没有

附：已知该代理地址可以直接返回正确内容，例如https://mydomain/picaapi.picacomic.com/返回和https://picaapi.picacomic.com/一致，我更想了解是不是程序内做了一些不支持这样做的设定

**Comment by MomentQYC** [comment]
这更应该不是bug，我可能需要就这个问题进行讨论，方便的话可以留一下能快速联系的方式

**Comment by tonquer** [comment]
用的分流一吗

**Comment by tonquer** [comment]
你是反代哔咔api，然后代码改了config.py里的Url吗

**Comment by MomentQYC** [comment]
> 你是反代哔咔api，然后代码改了config.py里的Url吗

应该是通过一个代理站进行访问
代理站我实测访问BaseURL和直接访问BaseURL效果一样（返回数据一模一样）

**Comment by tonquer** [comment]
那就是代理改了请求头，导致数据不对

**Comment by tonquer** [comment]
网页你没带header怎么测，返回的值没有参考价值

**Comment by tonquer** [comment]
你得用POST请求才行
