### ISSUE TITLE
使用Waifu2x时崩溃

### ISSUE THREAD

**Issue by ffffffffawd** [tonquer/picacg-qt#178]
### 操作系统（如MacOS 10.15）
>windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>在本子里使用Waifu2x崩溃

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
是所有的本子都一样吗，你的显卡型号是什么

**Comment by ffffffffawd** [comment]
amd 6500xt
什么本子都一样

**Comment by tonquer** [comment]
你的AMD驱动版本是不是大于[22.5.2](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-2)

**Comment by ffffffffawd** [comment]
我看看

**Comment by ffffffffawd** [comment]
我的readon software抽风了

**Comment by ffffffffawd** [comment]
我的readon software抽风了

**Comment by ffffffffawd** [comment]
怎么看

**Comment by tonquer** [comment]
你Radeon软件没法打开的吗

**Comment by ffffffffawd** [comment]
是的
说不兼容

**Comment by ffffffffawd** [comment]
但是我记得我装的是22.4.2

**Comment by ffffffffawd** [comment]
我重新下个技不如人勇气可嘉的驱动试试看

**Comment by ffffffffawd** [comment]
毕竟是它家的产品

**Comment by ffffffffawd** [comment]
现在我退回了22.1.2的版本
我去试试

**Comment by ffffffffawd** [comment]
现在无任何问题

**Comment by ffffffffawd** [comment]
不过建议您改进一下设置
换分流合并在设置界面里
毕竟登出在登入有些许麻烦

**Comment by ffffffffawd** [comment]
@tonquer

**Comment by tonquer** [comment]
后续设置中也可打开分流设置

**Comment by tonquer** [comment]
https://github.com/nihui/waifu2x-ncnn-vulkan/issues/178
