### ISSUE TITLE
各分流都是fail

### ISSUE THREAD

**Issue by TMR-TIKRIS** [tonquer/picacg-qt#179]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>各分流都是fail，使用了HTTPS代理http://127.0.0.1:10809还是fail，一二三都是

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
那可能你的地区不能直连，需要代理

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/discussions/48
