### ISSUE TITLE
大佬详情页作者名复制是不是有bug，右键显示复制但是c+v啥都没有，已最新版本

### ISSUE THREAD

**Issue by tcAllmight** [tonquer/picacg-qt#184]
### 操作系统（如MacOS 10.15）
>

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tcAllmight** [comment]
不过在详情页点击作者名字后能在作者页面复制

**Comment by tonquer** [comment]
v1.3.9已修复
