### ISSUE TITLE
部分本子中间有损坏的图片无法下载，会导致整个本子下载进程卡住

### ISSUE THREAD

**Issue by Phlogist** [tonquer/picacg-qt#185]
### 操作系统（如MacOS 10.15）
>windows

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>如题，某些本子中只有一个图片损坏，但是这个图片之后的所有图片都无法下载

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
比如哪一本呢

**Comment by Waldo-K-Maskelyne** [comment]
可能比如（剑风传奇(烙印战士)）？我这里下载状态显示（获取下载地址），进度0/0，章节28/36，就卡在这里。删掉重下还是这样。另外有个无伤大雅的小bug，有几本下载完成后我再次进入应用，下载状态显示（暂停），然后点开始全部下载秒变（下载完成），算是个显示bug吧？

**Comment by tonquer** [comment]
> 可能比如（剑风传奇(烙印战士)）？我这里下载状态显示（获取下载地址），进度0/0，章节28/36，就卡在这里。删掉重下还是这样。另外有个无伤大雅的小bug，有几本下载完成后我再次进入应用，下载状态显示（暂停），然后点开始全部下载秒变（下载完成），算是个显示bug吧？

这个问题是，这本子第29章是空白的，建议跳过该章下载
