### ISSUE TITLE
首页神推榜与魔推榜无法加载

### ISSUE THREAD

**Issue by Gaodgiaogiao** [tonquer/picacg-qt#186]
### 操作系统（如MacOS 10.15）
>Windows11 专业工作站版

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带

### 问题描述（简要描述发生的问题）
>进入首页后点击 神推榜/魔推榜选项卡 为空白页面

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>进入首页后点击 神推榜/魔推榜选项卡 为空白页面

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/72923189/180956129-50f1741e-e587-4403-9606-809c4aecaa36.png)

**Comment by tonquer** [comment]
你其他页面和登录正常吗

**Comment by Gaodgiaogiao** [comment]
都是正常的

**Comment by tonquer** [comment]
你这个日志没看到这个错误，如果只是显示空白，没有错误提示，可能哔咔返回就是空白
