### ISSUE TITLE
希望在右键菜单添加保存单张图片的功能

### ISSUE THREAD

**Issue by Autolenuants** [tonquer/picacg-qt#187]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 如标题所述，有时候看到一P特有意思，想直接保存下来，但发现只能完整下载，不是很方便

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by Autolenuants** [comment]
本张waifu2x也算一种变相的单张保存吧

**Comment by tonquer** [comment]
v1.3.9已支持
