### ISSUE TITLE
大佬我能登陆封面都显示但是点进去加载不出来

### ISSUE THREAD

**Issue by sdq1999** [tonquer/picacg-qt#188]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
能登录且能加载封面但是点进去就加载不出来 空白一片

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
换分流试试

**Comment by sdq1999** [comment]
分流也切换了 还是这样

**Comment by tonquer** [comment]
麻烦把软件目录下的logs目录日志文件上传一下

**Comment by heibaiqunhui** [comment]
[错误的20220808.log](https://github.com/tonquer/picacg-qt/files/9278279/20220808.log)
[正常的20220808.log](https://github.com/tonquer/picacg-qt/files/9278280/20220808.log)
![2022-08-08_104010](https://user-images.githubusercontent.com/43873213/183328537-4e3ac259-37e7-47b5-9924-21e4dadc0817.png)
我的也是不能加载详情页，重新下载换个目录能用，用的同一个config.ini。全部删除放在原目录偶尔能用，分流都试过，cdn也换过，删除db文件也不行，原目录路径：D:\!Green\bika\start.exe

Windows10 企业版 21H2 19044.1826 - WTG启动

电信宽带

**Comment by tonquer** [comment]
d

> [错误的20220808.log](https://github.com/tonquer/picacg-qt/files/9278279/20220808.log) [正常的20220808.log](https://github.com/tonquer/picacg-qt/files/9278280/20220808.log) ![2022-08-08_104010](https://user-images.githubusercontent.com/43873213/183328537-4e3ac259-37e7-47b5-9924-21e4dadc0817.png) 我的也是不能加载详情页，重新下载换个目录能用，用的同一个config.ini。全部删除放在原目录偶尔能用，分流都试过，cdn也换过，删除db文件也不行，原目录路径：D:!Green\bika\start.exe
> 
> Windows10 企业版 21H2 19044.1826 - WTG启动
> 
> 电信宽带

如何目录下的data/book.db不能删除

**Comment by heibaiqunhui** [comment]
> 

替换了正常的db文件，加载也有问题。

**Comment by heibaiqunhui** [comment]
确实是数据库损坏了，替换了 book.db 现在正常，但是不知道什么原因过会又损坏，SQLiteExpertProfessional打开也提示有问题。
![QQ图片20220809113857](https://user-images.githubusercontent.com/43873213/183558879-14248787-13b6-4009-ac9f-7e6dec612e0e.png)

**Comment by tonquer** [comment]
> 确实是数据库损坏了，替换了 book.db 现在正常，但是不知道什么原因过会又损坏，SQLiteExpertProfessional打开也提示有问题。 ![QQ图片20220809113857](https://user-images.githubusercontent.com/43873213/183558879-14248787-13b6-4009-ac9f-7e6dec612e0e.png)

麻烦上传下完整的日志文件，从正常到不正常的

**Comment by heibaiqunhui** [comment]
是同步软件 Synology Drive Client 把db独占了 
并且还原了之前的损坏的db文件
但是之前的db如何损坏的现在不确定
如果再发现 我会上传日志，谢谢！
