### ISSUE TITLE
更新本地数据库失败

### ISSUE THREAD

**Issue by Final-yuki** [tonquer/picacg-qt#191]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>可以直连，可以看本子，但是不能更新数据库，提示网络错误，请检查代理设置，请问是要求挂代理才能更新数据库吗？

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![QQ截图20220814123229](https://user-images.githubusercontent.com/65223406/184522573-9a1b025d-8c72
![QQ截图20220814123303](https://user-images.githubusercontent.com/65223406/184522585-73e90aeb-ad0e-4845-82a5-a1da55a8e586.png)
-42cc-af96-85a1c1ef36ae.png)
[20220814.log](https://github.com/tonquer/picacg-qt/files/9332697/20220814.log)

**Comment by tonquer** [comment]
v1.3.9新增了一个更新地址，解决部分地区无法更新问题
