### ISSUE TITLE
连接超时

### ISSUE THREAD

**Issue by aEGOz** [tonquer/picacg-qt#192]
### 操作系统（如MacOS 10.15）
>
win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信

### 问题描述（简要描述发生的问题）
>
前天开始所有的分流都连接超时

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
CDN分流也不行吗

**Comment by Final-yuki** [comment]
我也是，包括cdn在内的所有分流都上不去

**Comment by aEGOz** [comment]
> CDN分流也不行吗

不行

**Comment by tonquer** [comment]
> > CDN分流也不行吗
> 
> 不行

新加了个分流5，可以下载试试
https://github.com/tonquer/picacg-qt/actions/runs/2904329496

**Comment by aEGOz** [comment]
是的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月20日(星期六) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tonquer/picacg-qt] 连接超时 (Issue #192)





 
CDN分流也不行吗
