### ISSUE TITLE
读取收藏错误

### ISSUE THREAD

**Issue by CL-Sakura** [tonquer/picacg-qt#194]
### 问题描述（简要描述发生的问题）
>如图：收藏的本子无法正常读取，会出现下图的重复现象，并且不能读取其余全部的本子。

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/62274988/187089760-e5fc98e1-87af-4f71-801c-f6940118274d.png)

**Comment by tonquer** [comment]
请更新版本，最新版本已解决
