### ISSUE TITLE
保留漫畫信息到一個json文件中方便二次管理

### ISSUE THREAD

**Issue by chiyasakura** [tonquer/picacg-qt#195]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 保留漫畫信息如 漫畫名，作者名，分類標籤，上傳者，下載時間等信息到一個json文件中，方便用戶二次開發管理工具，也方便軟件的後續更新。
具體：
1：默認或設置可選，下載漫畫時將 信息json文件 保存到漫畫名的同名文件夾下。
2：或者提供一些調用漫畫信息的接口
*3：如果為了長效管理，也可在漫畫界面留出這一選項，當然這樣工作量會更大。

### 附加信息（其他的与功能相关的附加信息）
>   1.3.9版本之前沒有離線功能，所以使用第三方本地漫畫軟件來查看下載到本地的漫畫，但是量多起來之後就不好管理了。
也自己寫了一些腳本來管理，但是缺乏一些相關文件信息，不好分類，效果不盡人意。
但1.3.9版本后有離線功能了，所以也不是剛需，如果作者下次更新時，有餘力可以考慮加上這一功能，或者留出一些相關接口也
是極好的（比如內置的調試控制台）。最後，感謝作者有如此作品。

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
如果你只是想知道漫画信息的话，软件目录下data/book.db就是所以的漫画信息了，你可以用SQLiteStudio查看，或者用python解析

**Comment by chiyasakura** [comment]
谢谢！
tonquer ***@***.***> 于 2022年9月24日周六 21:28写道：

**Comment by chiyasakura** [comment]
我原先还以为那个文件是加密的，没多想

千夜樱 ***@***.***> 于 2022年10月17日周一 13:00写道：
