### ISSUE TITLE
章节名显示错误

### ISSUE THREAD

**Issue by Waldo-K-Maskelyne** [tonquer/picacg-qt#196]
### 操作系统（如MacOS 10.15）
>win11 21H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>目前仅在（极黑的布伦希尔特）一本中发现，详情页中缺少章节，下载页中只有四章（显示为1-3、7章，实际下载为1-4章）（安卓端正常显示及下载）

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20220901.log](https://github.com/tonquer/picacg-qt/files/9469618/20220901.log)

**Comment by tonquer** [comment]
v1.4.0修复了这个问题
