### ISSUE TITLE
希望为windows版本增加最小化到系统托盘功能

### ISSUE THREAD

**Issue by ctrl-altdel** [tonquer/picacg-qt#197]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望可以在设置中自由选择是最小化到任务栏还是系统托盘。因为有时挂机下载，总担心被人看到尴尬...

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>（图为使用第三方软件 ha_trayit! 实现的效果，但很不方便，还望软件能内置此功能）
![image](https://user-images.githubusercontent.com/76145868/188309707-2ad47d6b-de8a-4655-9003-37e728836d53.png)

**Comment by tonquer** [comment]
后续会添加，在点击关闭时弹出

**Comment by tonquer** [comment]
v1.4.0设置中以支持
