### ISSUE TITLE
希望能有一个批量下载的功能

### ISSUE THREAD

**Issue by Dylan001130** [tonquer/picacg-qt#198]
希望能够选择多个本子进行下载，每周好多本子一本一本下载太累了……就是比如ctrl然后点击就可以多选本子进行下载的样子？如果真的可以就特别感谢大佬了……

**Comment by huaiyi255** [comment]
非常赞同！！！！

**Comment by huaiyi255** [comment]
希望大佬能加一个

**Comment by DeanNevan** [comment]
+1

**Comment by tonquer** [comment]
![76903F3B](https://user-images.githubusercontent.com/22116659/192183026-dafc2b34-d2d0-4f14-a16a-efb18febc4ab.png)

**Comment by SG1048596-sy** [comment]
> ![76903F3B](https://user-images.githubusercontent.com/22116659/192183026-dafc2b34-d2d0-4f14-a16a-efb18febc4ab.png)
大佬您好，最近刚进入e站，首先非常感谢您制作的windows客户端，非常好用。
关于下载我有一个问题，希望您能在闲暇时给予回复
我进入了e站的里站，这时我看见了心仪的漫画，于是准备下载，这个下载需要消耗我所拥有的什么额度吗？因为我不是很了解e站的下载机制，在其他的论坛或网站看到了下载e站的本子需要消耗额度之类的。不知道这个下载是不是无限制的下载呢？
如果是的话，我就可以放心大胆的无限制下载啦！
最后，再一次感谢您所开发的客户端。

**Comment by tonquer** [comment]
> 

下载限制额度按时间自动恢复的，绑定ip地址。

**Comment by tonquer** [comment]
> > ![76903F3B](https://user-images.githubusercontent.com/22116659/192183026-dafc2b34-d2d0-4f14-a16a-efb18febc4ab.png)
> > 大佬您好，最近刚进入e站，首先非常感谢您制作的windows客户端，非常好用。
> > 关于下载我有一个问题，希望您能在闲暇时给予回复
> > 我进入了e站的里站，这时我看见了心仪的漫画，于是准备下载，这个下载需要消耗我所拥有的什么额度吗？因为我不是很了解e站的下载机制，在其他的论坛或网站看到了下载e站的本子需要消耗额度之类的。不知道这个下载是不是无限制的下载呢？
> > 如果是的话，我就可以放心大胆的无限制下载啦！
> > 最后，再一次感谢您所开发的客户端。

下载限制额度按时间自动恢复的，绑定ip地址。

**Comment by SG1048596-sy** [comment]
> > > ![76903F3B](https://user-images.githubusercontent.com/22116659/192183026-dafc2b34-d2d0-4f14-a16a-efb18febc4ab.png)
> > > 大佬您好，最近刚进入e站，首先非常感谢您制作的windows客户端，非常好用。
> > > 关于下载我有一个问题，希望您能在闲暇时给予回复
> > > 我进入了e站的里站，这时我看见了心仪的漫画，于是准备下载，这个下载需要消耗我所拥有的什么额度吗？因为我不是很了解e站的下载机制，在其他的论坛或网站看到了下载e站的本子需要消耗额度之类的。不知道这个下载是不是无限制的下载呢？
> > > 如果是的话，我就可以放心大胆的无限制下载啦！
> > > 最后，再一次感谢您所开发的客户端。
> 
> 下载限制额度按时间自动恢复的，绑定ip地址。

非常感谢您的回复

**Comment by tonquer** [comment]
v1.4.1已支持
