### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/picacg-qt#199]
软件版本为1.39，系统为win11专业版 21H2，网络为联通(访问网络正常)+v2rayN代理（全局+自动配置系统代理）（访问谷歌正常）

登录就报错，返回状态码400，或者连接超时，再或者无法连接，报错如下图：

![image](https://user-images.githubusercontent.com/52989379/191641654-785f546f-fefe-453e-96cc-1ed272344a01.png)

分流网络信息如下图：

![image](https://user-images.githubusercontent.com/52989379/191641778-565daddb-4faa-447d-94a3-84bf04d29762.png)

日志信息如下：

[20220922.log](https://github.com/tonquer/picacg-qt/files/9621579/20220922.log)

更换1.38版本后，报错结果相同

**Comment by tonquer** [comment]
登录错误的提示，哔咔返回的，翻译成中文就是，无效的账号或密码

**Comment by huaiyi255** [comment]
> 登录错误的提示，哔咔返回的，翻译成中文就是，无效的账号或密码

好嘞，谢谢，已经登录了
