### ISSUE TITLE
阅读进度跳转异常

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#201]
### 操作系统（如MacOS 10.15）
>WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>阅读进度N张M页，点进去之后跳转到第1章第1页

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>选择任意章节打开，关闭软件，再打开软件选择上次看到按钮，跳转到第1章第1页。

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/16437280/193485652-517798ce-84fe-4648-96c5-32c6e592cb93.png)

**Comment by tonquer** [comment]
v1.4.1已修复
