### ISSUE TITLE
最小托盘化图标重复

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#202]
### 操作系统（如MacOS 10.15）
>WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>最小托盘化图标可复数存在

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1、使用最小托盘功能
2、使用关闭按钮后再使用通知栏图标以外的方式打开软件

重复上述步骤

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/16437280/193879732-84376ec7-f513-4b6e-930c-f41672fa9415.png)

**Comment by tonquer** [comment]
v1.4.1已修复
