### ISSUE TITLE
Waifu2x功能无法使用

### ISSUE THREAD

**Issue by jogGUY** [tonquer/picacg-qt#205]
### 操作系统（如MacOS 10.15）
>
Windows7

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
校园网

### 问题描述（简要描述发生的问题）
>
1.登陆时提示“未找到Waifu2x组件”
2.Waifu2x组件功能无法使用

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
下载的本子点“开始转换”会报错，设置中waifu2x的开关都无法正常开启

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
2022-11-08 01:16:32 - task_waifu2x.py[line:123] - WARNING: Waifu2x convert error, taskId : 1, model: {}, err;

**Comment by jogGUY** [comment]
![Windows 7 x64-2022-11-08-01-17-06](https://user-images.githubusercontent.com/108516858/200378814-ca85328d-7ed8-4027-97bd-fd05b4794387.png)

**Comment by tonquer** [comment]
软件目录下logs目录有日志，请上传一下
请贴上你的cpu和显卡型号，登录提示waifu2x错误也截图一下

**Comment by jogGUY** [comment]
这里可能需要补充的是：运行软件的Win7是在虚拟机里，主机是Win11.
主机的CPU型号：AMD Ryzen 5 5600H；
主机的显卡型号：NVIDIA GeForce RTX 3050 Laptop GPU ( 4GB / 联想 )
虚拟机软件版本：VMware Workstation 15 Pro 15.5.7 build-17171714
日志文件：
[20221108.log](https://github.com/tonquer/picacg-qt/files/9956948/20221108.log)
[20221107.log](https://github.com/tonquer/picacg-qt/files/9956951/20221107.log)
登陆时的错误提示：
![Windows 7 x64-2022-11-08-09-47-43_看图王](https://user-images.githubusercontent.com/108516858/200456392-6a9c77da-6efe-4f6e-9674-8859e62c502c.png)

**Comment by tonquer** [comment]
![image](https://user-images.githubusercontent.com/22116659/200456893-d5b98fc2-bfa7-4d9f-86fc-4eb9bb850938.png)
请安装运行库试试

**Comment by jogGUY** [comment]
能用，我眼瞎了，给大佬磕个头 囧rz  o(￣┰￣*)ゞ
返回日志那只会看到这三行了：
2022-11-08 10:07:06,002 - start.py[line:61] - WARNING: init scene ratio: 1.25
2022-11-08 10:07:07,422 - setting_view.py[line:450] - WARNING: waifu2x GPU: None, select: CPU,use cpu num:  0
2022-11-08 10:07:07,422 - main_view.py[line:173] - WARING: waifu2x init: -1 encode: -1 version:1.1.4 code:0 cpuNum:0
看样子这是虚拟机调取不到显卡的毛病，这个我再去搜一下有没有解决办法......

**Comment by jogGUY** [comment]
另外偏个题，想问一下大佬未来会不会考虑支持看哔咔锅贴呢？

**Comment by tonquer** [comment]
> 能用，我眼瞎了，给大佬磕个头 囧rz o(￣┰￣*)ゞ 返回日志那只会看到这三行了： 2022-11-08 10:07:06,002 - start.py[line:61] - WARNING: init scene ratio: 1.25 2022-11-08 10:07:07,422 - setting_view.py[line:450] - WARNING: waifu2x GPU: None, select: CPU,use cpu num: 0 2022-11-08 10:07:07,422 - main_view.py[line:173] - WARING: waifu2x init: -1 encode: -1 version:1.1.4 code:0 cpuNum:0 看样子这是虚拟机调取不到显卡的毛病，这个我再去搜一下有没有解决办法......

nvidia应该只有专业卡才能支持虚拟化
