### ISSUE TITLE
pc端的缓存清理功能

### ISSUE THREAD

**Issue by legend418** [tonquer/picacg-qt#208]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 能一键清理搜索、下载、观看记录

### 附加信息（其他的与功能相关的附加信息）
> 今天想清理搜索记录发现不知道怎么清理，很难受

### 效果演示（可以提供可借鉴的图片）
>

**Comment by chiyasakura** [comment]
把那几个history文件删了就行，大概

**Comment by tonquer** [comment]
历史记录
data\history.db
下载记录
data\download.db
搜索记录
data\cache_word
设置
data\config.ini
缓存以及下载路径，在设置最下面显示

**Comment by legend418** [comment]
111
