### ISSUE TITLE
电脑端个别本子缺失

### ISSUE THREAD

**Issue by yemimang** [tonquer/picacg-qt#212]
### 操作系统（如MacOS 10.15）
>
win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
手机端的个别本子收藏  电脑端缺失 而且电脑端也搜索不到在电脑端通过作者名字也同样搜不到

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
对比两端比如三崎老师的金发妻 手机端有两个版本一个有码一个无修在手机上收藏好无修版本 然后在电脑端看不见这个无修的版本搜索作者名字也只有有码版本

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

![019baf11be3a11aec9a881b55cc4292](https://user-images.githubusercontent.com/122222002/211207960-05c6d0b2-7012-4420-8fec-65d0bc843653.jpg)
![aa5f99dabfe17c45fd259319043a459](https://user-images.githubusercontent.com/122222002/211207971-d1adae4b-c0af-4b92-bafb-92a5887b2a90.png)

**Comment by tonquer** [comment]
你发下帮助页面的版本信息看看，主要是本地数据库更新时间

**Comment by yemimang** [comment]
![4d91a572193bf6da75c4c4d06234198](https://user-images.githubusercontent.com/122222002/211241600-8f69c72d-72d8-4fdf-b7f5-16d863286774.png)

**Comment by tonquer** [comment]
你用搜索三崎也是搜不到这本是吧

**Comment by tonquer** [comment]
https://raw.bika.life/bika-robot/picacg-database/main/data2/book.db
下载这个，替换软件data目录下同名文件，应该可以暂时解决。

**Comment by yemimang** [comment]
是的搜作者中日名字都搜不到  
下了您给的文件问题解决了  辛苦了 非常感谢
