### ISSUE TITLE
【请教】你好，请问Pica的接口是怎么获取到的？

### ISSUE THREAD

**Issue by banmao999** [tonquer/picacg-qt#213]
你好，请问Pica的接口怎么获取？我曾尝试两种方式，最后都不行
1、拆包解析APK源码，经过反编译的源代码很难啃，最后放弃了
2、利用Fiddler抓取手机APP的请求，但因为挂上VPN后Fiddler就抓不到，最后也不行
想请教一下你是怎么抓取到的接口API？

另外，非常感谢你的项目 🚀🚀🚀👍👍👍👍👍

**Comment by tonquer** [comment]
接口用模拟器 httpcanry抓包
加密方式java反编译后发现是c++库，然后用IDA PRO反编译c++

**Comment by banmao999** [comment]
> 

学到了，谢谢你！❤
