### ISSUE TITLE
想要pc端修改头像功能

### ISSUE THREAD

**Issue by unrecyclablehuman** [tonquer/picacg-qt#214]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 想要可以上传图片修改头像的功能

### 附加信息（其他的与功能相关的附加信息）
> 这里用的是windows最新版本，没有找到相关入口，不知道是不是有但是我没找到TT 感谢！

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
点下头像，或者最下面其他-waifu2x
