### ISSUE TITLE
请问可以在软件里添加一个查看本地漫画的功能

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/picacg-qt#217]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在**其他**那一大项添加一个**本地漫画功能**，然后可以通过一个**打开**按钮，打开本地某个文件夹，之后会自动扫描其下所有文 件夹，并将其中的漫画在软件中显示出来，并可以通过双击直接打开阅读漫画

### 附加信息（其他的与功能相关的附加信息）
> 因为很多时候删除下载的记录后，就不能重新添加打开漫画了，还有大佬写的看漫画ui觉得非常nice，不想在其它软件来看漫画

### 效果演示（可以提供可借鉴的图片）
>
![image](https://user-images.githubusercontent.com/52989379/214563314-431df3a9-ec5e-4167-a4a2-cf1820801fb3.png)

**Comment by tonquer** [comment]
有这个打算

**Comment by tonquer** [comment]
v1.4.2已新增
