### ISSUE TITLE
自动打卡

### ISSUE THREAD

**Issue by matocool** [tonquer/picacg-qt#218]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 自动打卡

### 附加信息（其他的与功能相关的附加信息）
> 自动打卡

### 效果演示（可以提供可借鉴的图片）
>自动打卡

**Comment by mx41shy** [comment]
> 同时反馈下，当打开抽屉时候。右边的标签显示不完整。希望能加入自动换行。
> 
> 有的标签比较长，及时最大化依然不完整。
> 
> ![image](https://user-images.githubusercontent.com/83129369/214604926-0e265193-d5cf-473a-895e-000e01336bc1.png) ![image](https://user-images.githubusercontent.com/83129369/214605057-0bdcbdd9-d9af-4847-bb85-43f14de41e5f.png)

把鼠标移动到这一行，然后用滚轮滚动就可以看到后面的标签了
