### ISSUE TITLE
无法找到最新更新的本子

### ISSUE THREAD

**Issue by ChargerC** [tonquer/picacg-qt#219]
### 操作系统（如MacOS 10.15）
>
Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
在分区和收藏只能找到几天前更新的内容 最新更新的找不到 

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
打开分区和收藏找不到最新更新
![image](https://user-images.githubusercontent.com/63952499/215160582-2bbdc57e-8294-43b2-a91b-61453baf4b21.png)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
修复了 请重新打开软件

**Comment by ChargerC** [comment]
> 修复了 请重新打开软件

还是一样的情况

**Comment by ChargerC** [comment]
不知道是不是我的问题

**Comment by ChargerC** [comment]
啊 重装了一下 可以了 谢谢（（
