### ISSUE TITLE
能不能添加一个更换头像的功能？

### ISSUE THREAD

**Issue by RTR-RDD** [tonquer/picacg-qt#220]
### 功能描述
> 
如题，黑白头像太难受了。

**Comment by tonquer** [comment]
在工具 waifu2x里可以选图片更换

**Comment by RTR-RDD** [comment]
干啥？

**Comment by chiyasakura** [comment]
直接去官方手机端改就行

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
