### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by min152** [tonquer/picacg-qt#221]
### 操作系统（如MacOS 10.15）
>windo

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通宽带

### 问题描述（简要描述发生的问题）
>无法注册帐号

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>注册帐号时显示无法连接

[20230202.log](https://github.com/tonquer/picacg-qt/files/10568740/20230202.log)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
请更换分类后再尝试注册
