### ISSUE TITLE
能不能问一下你们都是怎么登陆上的  我一直显示无法连接或者出错误

### ISSUE THREAD

**Issue by 2361673592** [tonquer/picacg-qt#222]
### 操作系统（如MacOS 10.15）
>w11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动

### 问题描述（简要描述发生的问题）
>一直无法登录

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![Uploading a58cfe14f861358070f569391920bfd.png…]()

**Comment by tonquer** [comment]
按理来说分流和安卓端是一致的，请用分流三多登录试试
