### ISSUE TITLE
图片加载异常

### ISSUE THREAD

**Issue by Kano-I** [tonquer/picacg-qt#225]
### 操作系统（如MacOS 10.15）
> Windows 10_x64
> picacg  :  v1.4.1.1
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 电信 Wifi

### 问题描述（简要描述发生的问题）
> 图片加载异常，一张图片，一半能够正确加载，一半加载后非常模糊
> 已经持续一段时间了,刚开始使用还不会

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 大都是一些非全彩类漫画，几乎都会出现这种情况

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
> <img src="https://user-images.githubusercontent.com/104889317/217736342-789c4404-09ea-46b7-b3f6-2fd39d357f69.png" width="80%">
 [20230209.log](https://github.com/tonquer/picacg-qt/files/10694180/20230209.log)

**Comment by Kano-I** [comment]
下载下来后， 也是会模糊

**Comment by tonquer** [comment]
是大概率出现吗

**Comment by Kano-I** [comment]
> 是大概率出现吗

是的，现在每次看漫画 几乎都有类似的情况出现。下载下来也会 🤣

**Comment by Kano-I** [comment]
> 是大概率出现吗

我试着用虚拟机重新看了下，也是这种情况

**Comment by Yanxv-11** [comment]
我也是都出现了这种情况，而且全彩的也一样模糊 有的图片甚至模糊部分占到了9/10

**Comment by Yanxv-11** [comment]
我觉得就是跟网络有问题，我现在网络极其不稳定，只有线路二和反代分流显示能用，但是我切到线路二实际上又用不了，结果只有反代分流能用，但是反代分流有极其不好用，有的本子根本就加载不出来，加载出来的本子图片也是有问题的，至少一半的部分是模糊的。但是我觉得根本上是网络问题的原因是因为 当我用vpn的时候我上面说的所有问题就都没有了。

**Comment by Kano-I** [comment]
> 请删除cache目录，再试试这个问题还有没有出现了

现在不会出现这种情况了
