### ISSUE TITLE
图片不清晰和缩放率不保持的问题

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#229]
### 操作系统（如MacOS 10.15）
>WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>1.4.2更新后
1、waifu2x转换后图片仍然有明显的像素感。
2、修改缩放倍率后退出看图窗口再进入，缩放倍率由原来的在关闭应用之前保持不变，变为无法保持修改后的缩放倍率，不知道算bug还是更新内容。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>1、使用上下滚动模式，缩放倍率100%以上看图，有明显像素感。
2、修改缩放倍率后退出看图窗口再进入，缩放倍率恢复为100%

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/16437280/219729940-1da0deb3-69ad-4cc5-adf8-ee9b57f3be18.png)

**Comment by tonquer** [comment]
确实有这个问题 待修复

**Comment by tonquer** [comment]
v1.4.3已修复
