### ISSUE TITLE
随机推荐F5刷新键消失，点击F5也无法刷新

### ISSUE THREAD

**Issue by Alicelas** [tonquer/picacg-qt#231]
### 操作系统（如MacOS 10.15）
>WIN 11 22H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>1.4.2首页的随机推荐无法刷新

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1.点击首页
2.打开随机推荐

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![QQ截图20230220003824](https://user-images.githubusercontent.com/51156839/219961765-5c4eabb8-f3ac-4d28-94f4-f9b9d92d2356.jpg)

**Comment by tonquer** [comment]
一不小心删了，等下恢复

**Comment by tonquer** [comment]
v1.4.3已修复
