### ISSUE TITLE
请教与picaAPI服务器的连接思路

### ISSUE THREAD

**Issue by BiDuang** [tonquer/picacg-qt#232]
您好！阁下的项目对于picaAPI的研究和分析非常透彻，产品也非常地便捷好用。鄙人在研究阁下的源代码时发现国内大陆网络直接尝试请求picaAPI地址时会无法连接，应当是遭到了SNI拦截，但阁下的项目却可以正常地与picaAPI通信。步进分析后，我猜您似乎是采用了IP访问和DNS代理来连接吗？如果要迁移到使用 `aiohttp` 的项目上，我应该如何把 `urllib3` 上的实现转换呢？我一直没能想到好办法，因此来向您请教阁下的通讯思路、实现流程和建议。
如果您能百忙之中抽空施以援手，实在是万分感谢！
祝您工作生活顺利。

**Comment by tonquer** [comment]
以哔咔分流三为例
对于Api地址，指定dns解析
```188.114.98.153 picaapi.picacomic.com```
对于图片url，地址全部替换成
```storage.diwodiwo.xyz```

没有使用过aiohttp，不清楚能否实现自定义DNS，如果不能，需要自己修改系统的hosts文件

**Comment by BiDuang** [comment]
似乎picaAPI的IP地址会随时变动，您初始化的 `http://68.183.234.72/init` 是用于动态获取它的吗？
如果是这样，那固定hosts文件会对访问产生影响吗？

**Comment by tonquer** [comment]
是的，可以通过这个地址去动态更新，不过这些地址都是cloudflare的地址，只要这个ip没被屏蔽，一般都是可以用的。

**Comment by BiDuang** [comment]
好的，谢谢您
