### ISSUE TITLE
本地漫画自建文件夹或分类功能

### ISSUE THREAD

**Issue by NamelessHz** [tonquer/picacg-qt#233]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 自己也下载了很多漫画，想把pica作为漫画阅读器使用，但是在软件内的本地漫画导入后只有封面和名字，希望能够自建一些文件夹来对漫画进行整理，或者自己添加标签进行分类。

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
v1.4.3发布新增分流功能
