### ISSUE TITLE
mac的字体太小了，无法调整

### ISSUE THREAD

**Issue by littlewildcat** [tonquer/picacg-qt#235]
### 操作系统（如MacOS 10.15）
>3-inch, 2020, 13.2.1 (22D68)

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>SoftBack光

### 问题描述（简要描述发生的问题）
>macOS端的软件字体太小

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>软件版本：v1.4.1.1

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
软件设置里的字体大小无效吗，设置里的缩放调节也可以试试

**Comment by littlewildcat** [comment]
> 软件设置里的字体大小无效吗，设置里的缩放调节也可以试试

以下菜单字体无法调整：
用户
    我的收藏
    我的评论
    观看记录
导航
    首页
    搜索
    留言板
...
