### ISSUE TITLE
下载时源文件与转换文件不在同一目录

### ISSUE THREAD

**Issue by MyYuuka** [tonquer/picacg-qt#236]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>漫画源文件下载完成后重启客户端再进行转化，会导致转换文件的保存位置与源文件分开

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>将下载路径格式改为[作者名]作品名
方式一：下载漫画，同时开启转换 ——>源文件（original）和转换文件（waifu2x）都保存在.../commies/[作者名]作品名/ 中；
方式二：下载漫画但不进行转换，下载完成后关闭客户端——>此时源文件（original）和转换文件（waifu2x）保存在.../commies/[作者名]作品名/ 中；再次打开客户端（设置的下载格式仍然为[作者名]作品名），对下载完成的漫画进行转换——>转换文件（waifu2x）保存在.../commies/作品名/ 中；

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
v1.4.4已修复
