### ISSUE TITLE
希望添加图片清晰度选项

### ISSUE THREAD

**Issue by Discut** [tonquer/picacg-qt#237]
### 功能描述（请清晰的、详细的描述你想要的功能）
+ 希望能在下载漫画资源的功能中添加清晰度选项（原图、低、中、高），感觉这个应用浏览的图片并没有手机app获取的图片清晰 (；′⌒`)。

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以提供可借鉴的图片）
> ![image](https://user-images.githubusercontent.com/71692038/223356348-93718af0-fd89-47f8-b7e3-bb3937b77c97.png)

**Comment by tonquer** [comment]
一直都是原图画质，要对比清晰度要缩放到同一大小对比，放大本身就会模糊

**Comment by Discut** [comment]
> 一直都是原图画质，要对比清晰度要缩放到同一大小对比，放大本身就会模糊

确实，后来我测试了下，发现是浏览图片的控件放大了会模糊图片
![$SF}CH7AQ%FI7``2O(H5)XS](https://user-images.githubusercontent.com/71692038/223398764-610b91de-4e80-4394-8d03-5b50d632765c.png)

**Comment by tonquer** [comment]
目前上下滚动，等宽模式能放大到窗口大小，其他模式是最大高度，
超过就会模糊

这个为了流畅度的问题，还没有解决

**Comment by Discut** [comment]
谢谢答疑
