### ISSUE TITLE
我想在手机端也通过修改hosts文件,来加速访问picacg.

### ISSUE THREAD

**Issue by 1098346640** [tonquer/picacg-qt#238]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 通过修改hosts文件,来加速访问picacg.

### 附加信息（其他的与功能相关的附加信息）
> 我应该解析什么域名呢？

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
picaapi.picacomic.com
storage1.picacomic.com
img.picacomic.com
storage-b.picacomic.com
