### ISSUE TITLE
翻页使用上下滚动会出现回滚

### ISSUE THREAD

**Issue by AruHAna** [tonquer/picacg-qt#242]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>上下滚动看单行本等页数多的漫画，会在一定页数的时候出现回滚

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>观看单行本，等待大部分加载完，使用鼠标向下滚动，到达一定页数大概60-120时会出现在一定页数内回滚。
  离线下载好的单行本也会出现这种状况。

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
确实有这问题，待修复

**Comment by tonquer** [comment]
这个版本试试
https://github.com/tonquer/picacg-qt/releases/tag/v1.4.5

**Comment by AruHAna** [comment]
可以了，不会回滚了！感谢！
