### ISSUE TITLE
多个章节的本地漫画导入时，漫画图片导入不全

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/picacg-qt#244]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>导入本地漫画，存在多个章节漫画时，导入的图片不全

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>找一个章节大于10的漫画，例如：僵尸也能当bitch吗，下载完成后打开本地目录，直接导入此文件夹到本地漫画，或者拖动导入到本地漫画
![image](https://user-images.githubusercontent.com/52989379/229286572-6869b08e-929c-4a26-89ea-268482d53343.png)

漫画显示如下，存在363张图片，36个章节
![image](https://user-images.githubusercontent.com/52989379/229286628-c7616955-7712-47bb-a6cc-ac2c7e39513d.png)

此漫画实际成功导入的图片数
![image](https://user-images.githubusercontent.com/52989379/229286670-6eab2eea-790a-41b3-abb9-147b88ea3af4.png)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
多章节的漫画 正在支持

**Comment by tonquer** [comment]
已经支持
