### ISSUE TITLE
我想给我网站，做个一样的应用，想问问 接口返回数据结构和格式

### ISSUE THREAD

**Issue by 1439707509** [tonquer/picacg-qt#245]
能麻烦你提供下，接口返回数据的结构和格式，还有 下载时请求的api返回的结构

如果还有其它，用到的api返回格式，也麻烦提供下

如果愿意提供，或者需要报酬，请加下qq：1402259419

**Comment by tonquer** [comment]
代码已经是全部开源的，接口都在代码里有写

**Comment by 1439707509** [comment]
这是请求api，这里面肯定是不包含返回数据的格式结构的
如果是针对他们网站，直接修改打包没问题
如果是针对你的网站，就得让接口返回形式，和软件里要求的一致才行

外包的原话

**Comment by buiawpkgew1** [comment]
> 这是请求api，这里面肯定是不包含返回数据的格式结构的
> 如果是针对他们网站，直接修改打包没问题
> 如果是针对你的网站，就得让接口返回形式，和软件里要求的一致才行
> 
> 外包的原话

网站发一下看看

**Comment by 1439707509** [comment]
http://www.zerobyw4090.com/

**Comment by 1439707509** [comment]
> > 这是请求api，这里面肯定是不包含返回数据的格式结构的
> > 如果是针对他们网站，直接修改打包没问题
> > 如果是针对你的网站，就得让接口返回形式，和软件里要求的一致才行
> > 外包的原话
> 
> 网站发一下看看



> > 这是请求api，这里面肯定是不包含返回数据的格式结构的
> > 如果是针对他们网站，直接修改打包没问题
> > 如果是针对你的网站，就得让接口返回形式，和软件里要求的一致才行
> > 外包的原话
> 
> 网站发一下看看

http://www.zerobyw4090.com/
