### ISSUE TITLE
希望加入查看点过爱心的本子功能（？）

### ISSUE THREAD

**Issue by Yana-Hoshino** [tonquer/picacg-qt#247]
### 功能描述（请清晰的、详细的描述你想要的功能）

> 提供类似查看收藏的查看爱心功能

### 附加信息（其他的与功能相关的附加信息）

>感觉是不是哔咔没有相关接口，感觉会比较难做？  咱很想要来着（ 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
确实没有这个接口，用收藏不就可以了
