### ISSUE TITLE
忘记密码了怎么办

### ISSUE THREAD

**Issue by wxhecydxjj** [tonquer/picacg-qt#248]
有什么办法可以把本地文档里的密码解密出来吗？

**Comment by tonquer** [comment]
意思是你保存了密码，但是忘记了是么

**Comment by wxhecydxjj** [comment]
> > > 意思是你保存了密码，但是忘记了是么
> > 
> > 
> > 对的，我想在手机端使用，但是密码忘了
> 
> > > 意思是你保存了密码，但是忘记了是么
> > 
> > 
> > 对的，我想在手机端使用，但是密码忘了
> 
> 找个在线base64解码的网址https://www.toolhelper.cn/EncodeDecode/Base64EncodeDecode
> 
> 打开data/config.ini，Password一行 复制后面的字段，到网址上点，base64解码 ![image](https://user-images.githubusercontent.com/22116659/231780617-61d7e39e-767e-4267-8382-798e631e4adb.png)

谢谢好兄弟
