### ISSUE TITLE
本地漫画导入优化

### ISSUE THREAD

**Issue by Sakuralinyu** [tonquer/picacg-qt#249]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
能不能将下载的漫画自动导入本地漫画里面，大目录下希望支持自动载入子目录漫画
### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
更新v1.4.8

**Comment by Sakuralinyu** [comment]
谢谢，终于不用打开目录一本本添加了
