### ISSUE TITLE
无法连接

### ISSUE THREAD

**Issue by Kibelin07** [tonquer/picacg-qt#250]
### 操作系统（如MacOS 10.15）
>

window10
### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

移动
### 问题描述（简要描述发生的问题）
>无法连接

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>刚下载完

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://user-images.githubusercontent.com/122134428/235272118-b4bc1389-ef0c-4b5c-9e30-b7de6daf157a.png)

**Comment by EIKO4O4** [comment]
提交的都不算日志...我也遇到这个问题，发现是我账号密码记错了，输对密码就登进去了
