### ISSUE TITLE
关于翻页动作

### ISSUE THREAD

**Issue by mx41shy** [tonquer/picacg-qt#252]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
1、目前翻页动作如果到达第一页再向上翻页就会到上一章的第一页，有的时候看手滑往上一动滚轮就跳转到很多章以前了。
可不可以第一页往上翻跳转到上一章最后一页，最后一页往下翻到下一章第一页。
2、等宽模式时到达页顶部再往上翻就到上一页顶部，有的时候到页底部以为下面还有一点往下一翻，发现翻页了想回去又往上滚动回滚很多页。可不可以页顶部往上翻跳转到上一页底部，页底部往下翻到下一页顶部。

### 附加信息（其他的与功能相关的附加信息）
> 无

### 效果演示（可以提供可借鉴的图片）
>
![image](https://user-images.githubusercontent.com/16437280/235869184-0e8804d4-9dc6-4430-b4a3-babaeb8ba4e3.png)
honeyview有类似的设定，就是那个图片大于窗口时显示图片顶部，如果勾选的话和目前等宽模式是一样的，如果不勾选翻页时显示的是图片中部，或许可以把这个和翻页动作关联起来。

**Comment by tonquer** [comment]
应该是改的逻辑有问题，原来往前翻是会到最后一页的，也会翻到上一页的底部

**Comment by tonquer** [comment]
这个版本试试
https://github.com/tonquer/picacg-qt/releases/tag/v1.4.5
