### ISSUE TITLE
适配纵向显示器

### ISSUE THREAD

**Issue by D9Lose** [tonquer/picacg-qt#253]
### 操作系统（如MacOS 10.15）
>
Windows 21H2 19044.2913

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>
左侧屏幕1（竖屏）右侧屏幕2（横屏）
当哔咔在左侧最大化时正常，但是有概率会取消掉最大化状态，此时哔咔处于屏幕1和屏幕2之间 
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
打开哔咔 点击分区 点击本子 发现双击无反应，右键 打开 然后看完以后X退出，UI就不是最大化了，但是又不是完全的变形，所以有时候会很难察觉

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![8${`{RA}N( U$U1Q7RXN)AP](https://github.com/tonquer/picacg-qt/assets/39555559/e2db64d8-2172-4521-bd67-a06e560ab7ef)

右上角UI已经显示不完全了，已经不是最大化了

[20230521.log](https://github.com/tonquer/picacg-qt/files/11524436/20230521.log)

**Comment by tonquer** [comment]
多屏的 设置里勾选下使用默认标题栏
