### ISSUE TITLE
希望增加一个自定义图片预加载数量的功能

### ISSUE THREAD

**Issue by m2905076048** [tonquer/picacg-qt#257]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 目前加载类似于小说软件预加载，可以自定义在 阅读当前图片的时候加载好后面多少数量的图

### 附加信息（其他的与功能相关的附加信息）
> 
增加一个自定义是否预加载和预加载多少数量图片的开关
### 效果演示（可以提供可借鉴的图片）
>

**Comment by m2905076048** [comment]
或者同时加载多个图片，网卡的时候一个个加载好慢

**Comment by tonquer** [comment]
有预下载的，固定10页
