### ISSUE TITLE
> 希望可以针对已经下载的漫画，加入检查更新下载功能，感谢

### ISSUE THREAD

**Issue by JJrexWang** [tonquer/picacg-qt#260]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 希望可以针对已经下载的漫画，加入检查更新下载功能，感谢

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>
![image](https://github.com/tonquer/picacg-qt/assets/114320410/1a7b418d-70fa-4f6c-baf4-e257a6d89607)

**Comment by tonquer** [comment]
v1.4.8以支持
