### ISSUE TITLE
无法更新本地库

### ISSUE THREAD

**Issue by seiren-naru-shirayuri** [tonquer/picacg-qt#262]
### 操作系统（如MacOS 10.15）
>
Windows 10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
联通

### 问题描述（简要描述发生的问题）
>
无法更新本地库，导致某些漫画搜不到以及“最新更新”下的漫画不是最新，必须点搜索框取消“使用本地库”后才正常

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
点击“菜单-帮助”下的“检测更新”按钮后无反应，即时设置了代理也是如此

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![未命名](https://github.com/tonquer/picacg-qt/assets/56169262/a3c3e14a-ae87-4a92-8c41-c7f8a4f179a8)
[20230714.log](https://github.com/tonquer/picacg-qt/files/12050817/20230714.log)

**Comment by tonquer** [comment]
请打开使用本地数据库，重新检测更新试试

**Comment by seiren-naru-shirayuri** [comment]
试过了，没有用

**Comment by tonquer** [comment]
你更新了版本没有替换data目录吗，请重新下载覆盖

**Comment by seiren-naru-shirayuri** [comment]
单独删除data文件夹，下载最新安装包提取data文件夹覆盖后终于可以正常更新本地数据库了，谢谢作者的耐心解答，请关闭此issue。
