### ISSUE TITLE
搜索某分类作品时，获取不到最新的作品

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/picacg-qt#266]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>搜索某个分类时，最近更新的没有

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
1.在搜素框搜索cosplay，更新时间调整为降序，发现当前最近的就是71天前更新的
![image](https://github.com/tonquer/picacg-qt/assets/52989379/b8dafa4c-87bc-4e75-a813-4bd3431a521e)
![image](https://github.com/tonquer/picacg-qt/assets/52989379/fbea4805-4d83-43c8-bcca-1ef7c815db84)
2.进入哔咔在线版或者安卓版，以同样的方式搜索，最近更新的有三天前的
![image](https://github.com/tonquer/picacg-qt/assets/52989379/e6ce21b8-937e-46fb-bbf1-44b0ddd9b987)
3.在排行榜中 Vinnegal - Yor三天前才更新，但是最近更新搜不到
![image](https://github.com/tonquer/picacg-qt/assets/52989379/77eb26a1-a485-4b41-a236-a51e19998094)
![image](https://github.com/tonquer/picacg-qt/assets/52989379/dacbb043-a3e0-4220-b686-13d8bef684de)

**Comment by tonquer** [comment]
帮助界面看看本地库版本和时间
![image](https://github.com/tonquer/picacg-qt/assets/22116659/86886237-47ce-4e52-a8e1-d9f425e88ec0)

**Comment by huaiyi255** [comment]
本地库版本无法更新（网络试过本地，日本美国节点，可下载漫画）![image](https://github.com/tonquer/picacg-qt/assets/52989379/99a63829-7a20-4937-8d70-6182fdd0d64f)

**Comment by tonquer** [comment]
你是更新新版本没有覆盖data/book.db
可以重新下载覆盖

**Comment by huaiyi255** [comment]
ok，谢谢大佬

**Comment by huaiyi255** [comment]
已解决
![image](https://github.com/tonquer/picacg-qt/assets/52989379/cf396837-589c-4472-aa0a-daae00c42e2b)
