### ISSUE TITLE
本地漫画导入不全

### ISSUE THREAD

**Issue by huaiyi255** [tonquer/picacg-qt#267]
### 问题描述（简要描述发生的问题）
>当导入的文件夹中存在多个漫画文件夹时就会默认只读取第一个漫画文件夹，不会读取后续章节

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>找任意一个存在多个章节漫画的文件夹
![image](https://github.com/tonquer/picacg-qt/assets/52989379/bb84ad0a-d20d-4fe0-ae12-d10de4618192)
![image](https://github.com/tonquer/picacg-qt/assets/52989379/3a700678-df76-45c6-a64d-217a9855b1ed)
导入到picacg
![image](https://github.com/tonquer/picacg-qt/assets/52989379/1754cc9f-15ad-4e8a-8bc3-873f63648f04)
打开后只有第一章的内容，无法跳转下一章节
![image](https://github.com/tonquer/picacg-qt/assets/52989379/b17f6ac2-92c9-4163-b8c8-e42f01f3c1a1)

### 解决
希望能将添加一个读取章节的功能，将所有章节选择，之后就像阅读在线漫画一样，能够点击下一章时跳转到下一个章节

```python
import os,sys,natsort

def comic_list():
    # 获取到当前文件夹内所有漫画名
    path = os.path.dirname(__file__)
    path_names = os.listdir()
    path_names.remove(os.path.basename(sys.argv[0]))
    # 获取漫画的所有漫画名路径与对应章节名 形成一对对键值对 保存在一个字典内
    path_all = {}
    for i in path_names:
        path111 = path + '\\' +i + '\\original\\'
        dirlist = natsort.natsorted(os.listdir(str(path111)))
        path_all.update({str(path111):dirlist}) 
```

**Comment by tonquer** [comment]
你用的是1.4.6版本吗，已经加了导入多章节目录的功能

**Comment by huaiyi255** [comment]
> 你用的是1.4.6版本吗，已经加了导入多章节目录的功能

1.45😢

**Comment by huaiyi255** [comment]
Releases还没有更新，依然是1.45的版本

**Comment by tonquer** [comment]
帮助界面勾选接受beta更新试试

**Comment by huaiyi255** [comment]
ok，感谢大佬！
