### ISSUE TITLE
更换的字体无法正常应用

### ISSUE THREAD

**Issue by zcdswy** [tonquer/picacg-qt#269]
### 操作系统（如MacOS 10.15）
>win11

### 问题描述（简要描述发生的问题）
>更换的字体无法在标题栏、标签、搜索栏、设置等几乎所有文本处应用，但是可以正常应用于阅读界面首次开启的提示、加载图片时出现的页码和浮动进度条

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>尝试多次修改字体有关选项，大小粗细可正常调整，选择字体时出现如上问题

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
<img width="964" alt="Snipaste_2023-08-17_03-00-53" src="https://github.com/tonquer/picacg-qt/assets/98242488/e3becb38-0256-4aaf-8995-53a481d4d994">
<img width="963" alt="Snipaste_2023-08-17_02-31-02" src="https://github.com/tonquer/picacg-qt/assets/98242488/7a469745-ef33-410d-ae83-f7fdbc65ba6d">
<img width="953" alt="Snipaste_2023-08-17_02-36-52" src="https://github.com/tonquer/picacg-qt/assets/98242488/a6502055-afcf-495d-8e82-3cc0b87bcd86">
<img width="963" alt="Snipaste_2023-08-17_02-31-11" src="https://github.com/tonquer/picacg-qt/assets/98242488/1383d667-e2e0-46f7-af73-41bce8989d38">

**Comment by tonquer** [comment]
更新v.1.4.7试试

**Comment by zcdswy** [comment]
> 更新v.1.4.7试试

已解决，感谢 (*´∀`)bbb
