### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by aqswaqsw** [tonquer/picacg-qt#270]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>
不能登录

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

v1.4.5和v1.4.6都一样

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://github.com/tonquer/picacg-qt/assets/32766565/47747b56-da0e-4919-9168-9c84dc8f4163)

**Comment by tonquer** [comment]
这不是提示账号或密码错误了吗

**Comment by aqswaqsw** [comment]
前天还正常登录啊，用户名密码都没变
