### ISSUE TITLE
希望可以增加自动将下载记录中有更新的所有条目一键全选下载

### ISSUE THREAD

**Issue by 119278** [tonquer/picacg-qt#271]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 下载记录中有更新的所有条目，可以一键全选未选中的更新章节并自动开始下载

### 附加信息（其他的与功能相关的附加信息）
> 现阶段只能一个一个条目手动添加新更新章节进行下载

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
v1.4.8以支持
