### ISSUE TITLE
搜索功能BUG

### ISSUE THREAD

**Issue by yourpyfriend** [tonquer/picacg-qt#272]
### 操作系统（如MacOS 10.15）
>win10 专业版22H2

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>搜索出来的内容按照时间排序，大于7月12号之后的搜索不出来了

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>搜索任意内容

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by yourpyfriend** [comment]
经测试 1.4.4版本没这个问题，更新后出现。

**Comment by tonquer** [comment]
请确定你更新时，是否覆盖data/book.db，如果没覆盖，请重新下载
