### ISSUE TITLE
请求在workflows加入Linux打包

### ISSUE THREAD

**Issue by Z-fly** [tonquer/picacg-qt#276]

**Comment by tonquer** [comment]
我想用GLIBC 2.28版本打包，而workflows的ubuntu似乎只有2.27和2.29

**Comment by Z-fly** [comment]
这两个会导致打包失败吗？

**Comment by tonquer** [comment]
2.27打包运行不了，2.29打包没什么问题，只是部分老版本系统无法运行

**Comment by Z-fly** [comment]
目前的都是你自己手工打包的吗

**Comment by Z-fly** [comment]
![image](https://github.com/tonquer/picacg-qt/assets/10470892/0e614472-654e-4f90-9098-4a18b6a2ce99)
Linux可以像这样弄两个

**Comment by tonquer** [comment]
现在是手动打包

**Comment by Z-fly** [comment]
提供一个思路，拉一个Docker环境，在Docker里打包，这样打包出来是纯净的。
手工打包易混入其他文件

**Comment by tonquer** [comment]
已添加
