### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by Zousper** [tonquer/picacg-qt#277]
### 操作系统（如MacOS 10.15）
>windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动宽带

### 问题描述（简要描述发生的问题）
>1、注册时验证码图片无法加载，2、点击注册之后显示网络错误

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>1、注册时验证码图片无法加载 2、在邮箱等位置输入111填充，正常应返回邮箱错误等信息，但实际返回网络错误

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![image](https://github.com/tonquer/picacg-qt/assets/48244539/f3185c42-3c25-402a-80e4-801b1f9f9a75)
![image](https://github.com/tonquer/picacg-qt/assets/48244539/6e311b2d-9261-4bc4-85a0-62ae93ad988d)

**Comment by tonquer** [comment]
现在禁漫网页都有recaptcha验证了，请自行网页注册吧
