### ISSUE TITLE
本地漫画功能异常

### ISSUE THREAD

**Issue by DONGYO454** [tonquer/picacg-qt#278]
### 操作系统（如MacOS 10.15）
>Win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>主界面点进本地漫画时会卡住，等待几分钟后正常。本地漫画分组功能同样，删除漫画和分组会导致卡死，且无法删除第一个创建的分组。最大的问题，无法完全清除本地漫画，上述中第一个本地漫画分组无法被删除，导致始终存在已经不存在的漫画在加载导致卡死，尝试删除缓存解决卡死。无法解决。尝试卸载删除软件来清除本地漫画的数据，删除卸载级清除缓存均不能重置本地漫画，失效的第一分组内的所有漫画会在重新安装后仍然存在。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>建立一个本地漫画分组，导入漫画，卸载软件后重新安装上次的本地漫画分组和导入仍然存在

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20231110.log](https://github.com/tonquer/picacg-qt/files/13314081/20231110.log)
![Snipaste_2023-11-10_08-35-52](https://github.com/tonquer/picacg-qt/assets/149131577/657ea239-8ddd-46a1-8dff-bf11a40804ab)
![Snipaste_2023-11-10_08-39-33](https://github.com/tonquer/picacg-qt/assets/149131577/25c893fe-32a2-4157-9c88-f5f3de9acc1a)

**Comment by tonquer** [comment]
待处理

**Comment by tonquer** [comment]
v.1.4.7可以试试
