### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by ShadoWKamille** [tonquer/picacg-qt#280]
### 操作系统（如MacOS 10.15）
>win10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信宽带

### 问题描述（简要描述发生的问题）
>注册失败，返回值邮箱已存在，但注册界面没有填邮箱

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
![register_failed](https://github.com/tonquer/picacg-qt/assets/4270010/201d08f8-e966-45fe-b4bc-8c2e4e95b847)

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
账号就叫邮箱
