### ISSUE TITLE
新版本更新后出现本地数据库丢失

### ISSUE THREAD

**Issue by RTR-RDD** [tonquer/picacg-qt#283]
### 操作系统（如MacOS 10.15）
>windows11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>
新版本更新后本地数据库丢失

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
2023-12-03 17:15:55,702 - help_view.py[line:109] - ERROR: Not found book.db !!!!!!!!!!!!!!!
![79b54864d174fcd403bf67fb71e4f95](https://github.com/tonquer/picacg-qt/assets/63495998/2afe6741-510b-431e-9bd4-c31016b1fa4b)

**Comment by tonquer** [comment]
请确定解压是否正常，压缩包里是有该文件的

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by RTR-RDD** [comment]
这是来自QQ邮箱的假期自动回复邮件。



    
        你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by HowieHz** [comment]
> 请确定解压是否正常，压缩包里是有该文件的

这个数据库是存什么的，更新覆盖会使配置出问题吗

**Comment by RTR-RDD** [comment]
干啥？
