### ISSUE TITLE
下载一直报错，连接没问题，点进去也能看，就是下不下来，一直错误

### ISSUE THREAD

**Issue by tikko-now** [tonquer/picacg-qt#289]
### 操作系统（如MacOS 10.15）
>win11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>联通

### 问题描述（简要描述发生的问题）
>下载一直报错，连接没问题，点进去也能看，就是下不下来，一直错误
### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
哪本下不了，日志也上传下看看

**Comment by tikko-now** [comment]
[20240110.log](https://github.com/tonquer/picacg-qt/files/13886435/20240110.log)
今天挂着下载自动重试下了一天（又新追加了100本），除了基本几千页的报错我删除了，剩下的到刚刚才下完

**Comment by tonquer** [comment]
会优化，下载超时自动重试

**Comment by tonquer** [comment]
1.4.8已优化可以试试
https://github.com/tonquer/picacg-qt/releases/tag/v1.4.8

**Comment by tikko-now** [comment]
收到，明天试试

**Comment by tikko-now** [comment]
下载不会报错了
