### ISSUE TITLE
有的本子明明没有下载完，反而显示下载完成

### ISSUE THREAD

**Issue by tikko-now** [tonquer/picacg-qt#292]
![image](https://github.com/tonquer/picacg-qt/assets/94343527/d08439df-2218-45a8-bf3e-b0f1ac6226ad)
这本的第五章只下载了一页（本子名称ハーレム・カルト (コミックホットミルク 2020年1月号) [中国翻訳] [DL版]），却显示下载完成，还有一本只有一章的，只下载了一页就显示结束了，我下了2000多本，不知道有多少是这个情况，要崩溃了

**Comment by tonquer** [comment]
> ![image](https://private-user-images.githubusercontent.com/52989379/313683465-ef75d678-29b2-4133-b8c9-a5181bd86434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTc4MjIsIm5iZiI6MTcxMjM5NzUyMiwicGF0aCI6Ii81Mjk4OTM3OS8zMTM2ODM0NjUtZWY3NWQ2NzgtMjliMi00MTMzLWI4YzktYTUxODFiZDg2NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA5NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjdjMmRmODZlMTZhMTE0Y2ZiM2QwYzYxZWVlYTg1NjNhMGU1MzFkOGM2OGM4YjljOWNjNjA3ODMwNDYzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzjdWixFYqvX34lxegM7rjFu2OR3AJol7H1ggs6nTI8) 同样的情况

如果能复现，可以把设置日志等级设置为Debug，复现后可以把log文件发我邮箱tonquer@qq.com

**Comment by huaiyi255** [comment]
> > ![image](https://private-user-images.githubusercontent.com/52989379/313683465-ef75d678-29b2-4133-b8c9-a5181bd86434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTc4MjIsIm5iZiI6MTcxMjM5NzUyMiwicGF0aCI6Ii81Mjk4OTM3OS8zMTM2ODM0NjUtZWY3NWQ2NzgtMjliMi00MTMzLWI4YzktYTUxODFiZDg2NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA5NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjdjMmRmODZlMTZhMTE0Y2ZiM2QwYzYxZWVlYTg1NjNhMGU1MzFkOGM2OGM4YjljOWNjNjA3ODMwNDYzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzjdWixFYqvX34lxegM7rjFu2OR3AJol7H1ggs6nTI8) 同样的情况
> 
> 如果能复现，可以把设置日志等级设置为Debug，复现后可以把log文件发我邮箱[tonquer@qq.com](mailto:tonquer@qq.com)

师傅您好，已复现发送

**Comment by tonquer** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/52989379/313683465-ef75d678-29b2-4133-b8c9-a5181bd86434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTc4MjIsIm5iZiI6MTcxMjM5NzUyMiwicGF0aCI6Ii81Mjk4OTM3OS8zMTM2ODM0NjUtZWY3NWQ2NzgtMjliMi00MTMzLWI4YzktYTUxODFiZDg2NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA5NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjdjMmRmODZlMTZhMTE0Y2ZiM2QwYzYxZWVlYTg1NjNhMGU1MzFkOGM2OGM4YjljOWNjNjA3ODMwNDYzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzjdWixFYqvX34lxegM7rjFu2OR3AJol7H1ggs6nTI8) 同样的情况
> > 
> > 
> > 如果能复现，可以把设置日志等级设置为Debug，复现后可以把log文件发我邮箱[tonquer@qq.com](mailto:tonquer@qq.com)
> 
> 师傅您好，已复现发送

你这本是日志前已经出现了吧，有没有新添加下载出现1的

**Comment by huaiyi255** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/52989379/313683465-ef75d678-29b2-4133-b8c9-a5181bd86434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTc4MjIsIm5iZiI6MTcxMjM5NzUyMiwicGF0aCI6Ii81Mjk4OTM3OS8zMTM2ODM0NjUtZWY3NWQ2NzgtMjliMi00MTMzLWI4YzktYTUxODFiZDg2NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA5NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjdjMmRmODZlMTZhMTE0Y2ZiM2QwYzYxZWVlYTg1NjNhMGU1MzFkOGM2OGM4YjljOWNjNjA3ODMwNDYzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzjdWixFYqvX34lxegM7rjFu2OR3AJol7H1ggs6nTI8) 同样的情况
> > > 
> > > 
> > > 如果能复现，可以把设置日志等级设置为Debug，复现后可以把log文件发我邮箱[tonquer@qq.com](mailto:tonquer@qq.com)
> > 
> > 
> > 师傅您好，已复现发送
> 
> 你这本是日志前已经出现了吧，有没有新添加下载出现1的

没有，在新添加下载时，尝试复现未能成功，可能是需要大量的资源一起下载时才会出现

**Comment by tonquer** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/52989379/313683465-ef75d678-29b2-4133-b8c9-a5181bd86434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTc4MjIsIm5iZiI6MTcxMjM5NzUyMiwicGF0aCI6Ii81Mjk4OTM3OS8zMTM2ODM0NjUtZWY3NWQ2NzgtMjliMi00MTMzLWI4YzktYTUxODFiZDg2NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA5NTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMjdjMmRmODZlMTZhMTE0Y2ZiM2QwYzYxZWVlYTg1NjNhMGU1MzFkOGM2OGM4YjljOWNjNjA3ODMwNDYzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzjdWixFYqvX34lxegM7rjFu2OR3AJol7H1ggs6nTI8) 同样的情况
> > > > 
> > > > 
> > > > 如果能复现，可以把设置日志等级设置为Debug，复现后可以把log文件发我邮箱[tonquer@qq.com](mailto:tonquer@qq.com)
> > > 
> > > 
> > > 师傅您好，已复现发送
> > 
> > 
> > 你这本是日志前已经出现了吧，有没有新添加下载出现1的
> 
> 没有，在新添加下载时，尝试复现未能成功，可能是需要大量的资源一起下载时才会出现

尝试修复了，可以试试
https://github.com/tonquer/picacg-qt/actions/runs/8601399194
