### ISSUE TITLE
1920*1080竖屏模式下，窗口最大化时偶尔尺寸有问题，超出屏幕显示。

### ISSUE THREAD

**Issue by 66247** [tonquer/picacg-qt#294]
### 操作系统（如MacOS 10.15）
>Windows11

### 问题描述（简要描述发生的问题）
>1920*1080竖屏模式下 排列有问题，以前在1920*1200下一直正常。
窗口切换最大化模式后  正常显示2列，漫画尺寸正常 ，能看到右上角三个图标（最小化、最大化、关闭），右下角刷新按钮正常
浏览漫画后偶尔会一下变成3列，右上角3个图标消失，右下角刷新按钮消失，漫画超出屏幕边界（显示不全），重新缩放窗口后恢复正常。
标题栏美化开启和关闭都会出现异常。
标题栏美化开启：
出现异常，刷新按钮能不见了，右上角最小化、最大化、关闭不见了
![异常](https://github.com/tonquer/picacg-qt/assets/33511467/2429412c-dcdb-44af-aa88-2efdfc462cf7)
缩放后正常，刷新按钮能看到，右上角最小化、最大化、关闭正常
![正常](https://github.com/tonquer/picacg-qt/assets/33511467/6a391539-1e3b-487e-b2d4-3929098cb830)

标题栏美化关闭：
出现异常，刷新按钮能不见了
![异常1](https://github.com/tonquer/picacg-qt/assets/33511467/6a805f24-74a9-45dc-bd4d-b7bcf213b8ae)
缩放后正常，刷新按钮能看到
![正常2](https://github.com/tonquer/picacg-qt/assets/33511467/793bcb1e-a488-46d9-91ca-1fc443466d4f)

**Comment by tonquer** [comment]
修复了试试
https://github.com/tonquer/picacg-qt/releases/tag/v1.4.9

**Comment by 66247** [comment]
正常了，更新后未在出现问题。
