### ISSUE TITLE
报错：{"code":500, "error":“MISCONF Redis is configured to save RDB snapshot but it is currently not able to presist on disk. Commands that may modify.....

### ISSUE THREAD

**Issue by CV90105** [tonquer/picacg-qt#295]
### 操作系统（如MacOS 10.15）
>
WIN11

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
WIFI

### 问题描述（简要描述发生的问题）
>
登录时显示{"code":500, "error":“MISCONF Redis is configured to save RDB snapshot but it is currently not able to presist on disk.

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
可能是不小心删了什么文件导致的，但不清楚是啥文件

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20240202.log](https://github.com/tonquer/picacg-qt/files/14146206/20240202.log)

**Comment by tonquer** [comment]
这是bika返回的错误提示
