### ISSUE TITLE
全屏时窗口大小比实际屏幕大,使图片的一部分超过屏幕显示在外

### ISSUE THREAD

**Issue by AsAoA801** [tonquer/picacg-qt#301]
### 操作系统（如MacOS 10.15）
>windows 10 surface

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>电信

### 问题描述（简要描述发生的问题）
>窗口大小比实际屏幕大,使图片的一部分超过屏幕显示在外
另外,窗口化窗口的最小大小也超过屏幕无法缩小,不知道是不是同一个问题

我使用surface经常出现此问题, 导致根本无法使用全屏观看, 还请修复!

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>1.确保只有一个显示器
2.以横屏打开bika
3.将窗口显示方向改成竖向

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
![clipboard-image-1713008682](https://github.com/tonquer/picacg-qt/assets/130402344/bd7e5911-fc89-475f-854d-d0e3a1598971)

**Comment by tonquer** [comment]
你的分辨率和缩放是多少

**Comment by AsAoA801** [comment]
> 你的分辨率和缩放是多少

我的surface是1800x1200,
我在1920x1080的笔记本上也复现了.
但在2560x1440的外接显示器上无法复现,没有显示问题.

**Comment by tonquer** [comment]
修复了试试
https://github.com/tonquer/picacg-qt/releases/tag/v1.4.9
