### ISSUE TITLE
在上下、左右滚动阅读模式下缩放图片存在图片质量问题

### ISSUE THREAD

**Issue by Dis0rder445** [tonquer/picacg-qt#308]
### 操作系统（如MacOS 10.15）
>windows10

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>

### 问题描述（简要描述发生的问题）
>在上下、左右滚动模式下缩放图片时，图片有严重锯齿且缩放比例异常，上下滚动模式下缩放比例为50%时，图片显示尺寸大于默认模式下100%缩放的显示尺寸

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>

**Comment by tonquer** [comment]
有锯齿发下图看看

**Comment by Dis0rder445** [comment]
![屏幕截图 2024-05-31 095053](https://github.com/tonquer/picacg-qt/assets/140158560/7eb125da-6754-4b10-90ae-67fe68891e00)

![屏幕截图 2024-05-31 095112](https://github.com/tonquer/picacg-qt/assets/140158560/9aa1758b-5f23-4bca-9406-04812ca3c9b0)
图一为上下滚动模式，50%缩放。图二为默认模式100%缩放

**Comment by Dis0rder445** [comment]
![屏幕截图 2024-05-31 095435](https://github.com/tonquer/picacg-qt/assets/140158560/5ffa323c-02db-41fe-a7c2-22235bc405e0)
上下滚动模式80%缩放，线条有明显锯齿

**Comment by Dis0rder445** [comment]
![屏幕截图 2024-05-31 095727](https://github.com/tonquer/picacg-qt/assets/140158560/9da3125b-10c0-4867-95e1-b229cb26b9e2)
黑白本线条锯齿更加明显

**Comment by tonquer** [comment]
确实有问题，下版本修复

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/releases/tag/v1.5.0
已尝试修复
