### ISSUE TITLE
指定标签过滤

### ISSUE THREAD

**Issue by QiuLiang-99** [tonquer/picacg-qt#310]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 在标签筛选功能中，点击一次之后，该标签为选中状态，再点击一次后，标签变为被排除状态，搜索到的漫画如果含有被排除的标签则会被过滤，不显示

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by QiuLiang-99** [comment]
有一个简单的方法实现这个feature就是在search_view.py的123行替换为如下代码      
`for name in ["耽美", "伪娘", "禁书", "扶她", "重口", "生肉", "纯爱", "SM", "NTR", "WEBTOON","CG杂图"]:`
我认为这能起作用

**Comment by alinzhou20** [comment]
同感，另外search_view.py的123行屏蔽词不全

**Comment by alinzhou20** [comment]
另外无法进行多标签的屏蔽

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/releases/tag/v1.5.0
已修改
