### ISSUE TITLE
希望可以在观看漫画时，显示当前的章节信息

### ISSUE THREAD

**Issue by sink-er** [tonquer/picacg-qt#312]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 
希望可以在观看漫画时，显示当前的章节信息

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>
![PixPin_2024-06-28_22-49-18](https://github.com/tonquer/picacg-qt/assets/53322400/d14f6464-7c26-46e8-9d87-c647f427060e)
![PixPin_2024-06-28_22-52-24](https://github.com/tonquer/picacg-qt/assets/53322400/c36189dd-fb03-4d57-aea9-8a830c8b3eb4)

**Comment by tonquer** [comment]
https://github.com/tonquer/picacg-qt/releases/tag/v1.5.0
已支持
