### ISSUE TITLE
打开后窗口自动吸附在桌面的上方不能移动

### ISSUE THREAD

**Issue by QiuLiang-99** [tonquer/picacg-qt#313]
### 操作系统（如MacOS 10.15）
>win11

### 问题描述（简要描述发生的问题）
>窗口会自动被吸附到上边，缩小化窗口化关闭这三个按钮会消失，窗口无法移动，使用鼠标指针调整一次窗口大小后恢复

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>打开软件

**Comment by tonquer** [comment]
你是多屏吗，系统分辨率和缩放设置是多少

**Comment by QiuLiang-99** [comment]
不是，分辨率2560×1440，缩放125%

**Comment by QiuLiang-99** [comment]
> 你是多屏吗，系统分辨率和缩放设置是多少

不是，分辨率2560×1440，缩放125%

**Comment by QiuLiang-99** [comment]
1.5.1.1版本此bug已修复
