### ISSUE TITLE
使用waifu2x会造成闪退

### ISSUE THREAD

**Issue by yhd9487** [tonquer/picacg-qt#316]
### 操作系统（如MacOS 10.15）
> Windows11 23H2 22631.3880

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
> 联通

### 问题描述（简要描述发生的问题）
> 尝试使用waifu2x时发生闪退，具体情况为在使用过程中只要程序调用waifu2x处理：封面，下载后进行转换或是看图都会导致程序在大约5秒后闪退。

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
> 在设置中启用任意waifu2x设定，在主页浏览，点进漫画后看图或是在漫画下载后调用waifu2x进行转换，程序调用waifu2x处理图片，GPU开始处理任务，大约5秒后必定闪退，目前初步推断为waifu2x对AMD核显的适配有问题，因为waifu2x使用CPU并没有这种情况发生。
CPU：AMD R7 8845H，GPU: AMD Radeon 780m

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
> 
[20240724.log](https://github.com/user-attachments/files/16360799/20240724.log)

**Comment by yhd9487** [comment]
进一步推断，是下载好之后转换这部分有问题（模型设置为cunet），不论是调用CPU还是GPU都会导致闪退，看图和封面（模型设置为Auto）没有问题。

**Comment by tonquer** [comment]
设置里调低Tile值试试

**Comment by yhd9487** [comment]
问题解决了，经过测试，Tile设置成100，使用GPU转换下载好的漫画不会再闪退了。
