### ISSUE TITLE
不好意思，这个自动翻页功能是怎么开啊？没看见有什么开关键，也不太懂 github 就直接标题问了

### ISSUE THREAD

**Issue by CLOVEDY** [tonquer/picacg-qt#323]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by Yi1Nai** [comment]
哥们请教一下，我现在也不知道怎么开自动翻页

**Comment by tonquer** [comment]
> 哥们请教一下，我现在也不知道怎么开自动翻页

右键菜单里有 或者f5
