### ISSUE TITLE
现在已有的waifu2x模型就三个，可以自己更换吗，要怎么操作

### ISSUE THREAD

**Issue by 847361092** [tonquer/picacg-qt#326]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 就是比如说：看图的时候想换成用real-ESRGAN模型，但自己又不知道去哪里换或者添加进去使用。

### 附加信息（其他的与功能相关的附加信息）
> 
<img width="380" alt="截屏2024-09-13 15 43 22" src="https://github.com/user-attachments/assets/d5577914-1f98-499c-9a97-bf03bb7bc818">

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
不能，目前只移植了[waifu2x](https://github.com/tonquer/waifu2x-vulkan)，real-ESRGAN不是waifu2x的模型

**Comment by tonquer** [comment]
现已支持
