### ISSUE TITLE
appimage无法运行

### ISSUE THREAD

**Issue by shibuyameltdown** [tonquer/picacg-qt#335]
### 操作系统（如MacOS 10.15）
>debian12

### 问题描述（简要描述发生的问题）
>用的是tiny computer（在安卓上运行debian12）🤔
![4C6D45002F676DE6B12A963570685B38](https://github.com/user-attachments/assets/7d5ffd93-c523-46fb-8769-21b9d63f4f39)

**Comment by shibuyameltdown** [comment]
是因为架构不对吗🤔

**Comment by tonquer** [comment]
是原生arm吗，这个包是x86的不支持arm

**Comment by shibuyameltdown** [comment]
> 是原生arm吗，这个包是x86的不支持arm

收到，terminal看是aarch64，应该是arm吧
