### ISSUE TITLE
左侧导航的分类栏中只有前两项

### ISSUE THREAD

**Issue by sink-er** [tonquer/picacg-qt#336]
### 操作系统（如MacOS 10.15）
>
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2023/‎8/‎11
操作系统版本	22631.4391
体验	Windows Feature Experience Pack 1000.22700.1047.0

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
移动宽带

### 问题描述（简要描述发生的问题）
>
左侧导航的分类栏中只有前两项，该问题只在Ver.1.5.1出现，昨天出现，今天也出现

https://github.com/user-attachments/assets/edf3d8dd-e684-4898-af9f-57790cb0cc27

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
不清楚是什么原因导致的

### 日志提交（问题截图或者日志，日志在设置中设置为INFO，在帮助界面打开日志目录）
>
[20241029.log](https://github.com/user-attachments/files/17557756/20241029.log)

**Comment by tonquer** [comment]
修复了请重新下载
https://github.com/tonquer/picacg-qt/releases/tag/v1.5.1
