### ISSUE TITLE
waifu问题

### ISSUE THREAD

**Issue by luzebillan** [tonquer/picacg-qt#72]
命令行中报错：
DLL load failed while importing waifu2x: 找不到指定的模块。
怀疑是import方式问题
改为：
from ctypes import CDLL
waifu2x = CDLL("./waifu2x.so")
后依旧报错：
[WinError 193] %1 不是有效的 Win32 应用程序。
请问您的waifu2x.so文件是32位的嘛？

**Comment by tonquer** [comment]
waifu2x已经上传到pypi，模块修改为waifu2x_vulkan，请更新git代码，  
如果你安装了vs可以使用 pip install waifu2x_vulkan 编译安装。  
如果没有请使用 pip install waifu2x_vulkan==1.0.4 安装编译好的文件

**Comment by LuzeBillan** [comment]
感谢
