### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by ImZhou666** [tonquer/picacg-qt#95]
> 在v1.2.9.1中，从漫画详情页点击作者名跳转到搜索页时，能把作者名在搜索栏进行填充吗？前一个版本是有这个的，可以进行选中、复制以及修改，新版本似乎把这个删了，，，总有人不会打日文吧

**Comment by tonquer** [comment]
加上了
https://github.com/tonquer/picacg-qt/actions/runs/1512230283
