### ISSUE TITLE
[BUG]排行榜重复加载

### ISSUE THREAD

**Issue by xmhwws** [tonquer/picacg-qt#96]
win10
最新版

在排行榜，比如说选24小时拉到最下面，再点击7天，然后再点击24小时，会发现它重复加载，且之前加载的没清空
![2021-11-28_21-34-50](https://user-images.githubusercontent.com/42903751/143770084-a0c7b84f-a0b5-421b-a997-569fbed59f31.png)

另外提个功能推荐：apk应该有本地数据库记录观看下载等记录，bika的观看记录是在本地，服务器不记录；
能否将apk的观看记录导入软件（提醒数据库在手机哪个目录下，把数据库复制到电脑，软件再解析数据库）呢？如果观看记录和电脑端记录有冲突，提示，让用户选择保留哪一个记录；

**Comment by tonquer** [comment]
akp的观看记录同步可以尝试下

**Comment by xmhwws** [comment]
@tonquer 最新版，发现一个比较奇特的bug，画面左端有时会显示上一次观看的漫画图片的内容
![2021-12-05_12-06-59](https://user-images.githubusercontent.com/42903751/144733076-01e78b92-062a-4c37-babe-008d711ac0e0.jpg)
![2021-12-05_12-07-32](https://user-images.githubusercontent.com/42903751/144733081-acfcb738-0f4d-4ce7-a3a1-4f66f8e1720a.jpg)

**Comment by tonquer** [comment]
已尝试修复，但可能会显示错误的编号
