### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by an040307** [tonquer/picacg-qt#97]
### 操作系统（如MacOS 10.15）
>windows

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>移动

### 问题描述（简要描述发生的问题）
>无法打开

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>双击start.exe

### 日志提交（问题截图或者日志，日志在logs目录）
>
![image](https://user-images.githubusercontent.com/88210581/143770453-29751cd1-1133-403a-9ba3-8590de65bdab.png)

**Comment by tonquer** [comment]
尝试修复了，可以下载试试
https://github.com/tonquer/picacg-qt/actions/runs/1514886481
