### ISSUE TITLE
[BUG]无法使用waifu2x的问题

### ISSUE THREAD

**Issue by jikezhuanqing** [tonquer/picacg-qt#98]
### 操作系统（如MacOS 10.15）
>
Windows11（21H2）

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信宽带

### 问题描述（简要描述发生的问题）
>
自从更新了1.2.7支持CPU转换功能后一直无法正常转换

### 复现步骤（详细描述导致问题产生的操作步骤，如果能稳定复现）
>
看图和下载一直显示转换中；
debug显示：[waifu2x] not found path C:\Users\鏄€\AppData\Local\Temp\_MEI106242\waifu2x_vulkan/models/models-upconv_7_anime_style_art_rgb/noise3_scale2.0x_model.param
我的文件路径：C:\Users\昀\AppData\Local\Temp\_MEI106242\waifu2x_vulkan\models\models-upconv_7_anime_style_art_rgb\noise3_scale2.0x_model.param

### 日志提交（问题截图或者日志，日志在logs目录
[debug.txt](https://github.com/tonquer/picacg-qt/files/7614098/debug.txt)

**Comment by tonquer** [comment]
尝试修复了，可以试试
https://github.com/tonquer/picacg-qt/actions/runs/1514851777

**Comment by jikezhuanqing** [comment]
可以使用了，大感谢，新的UI很棒噢
