### ISSUE TITLE
[Feature Request] 关于分类中是否有“全部”

### ISSUE THREAD

**Issue by shalamanZH** [tonquer/picacg-qt#99]
### 功能描述（请清晰的、详细的描述你想要的功能）
> 像是原版分类中“最近更新”，可以按照时间顺序浏览全部的列表，而不是固定分类浏览

### 附加信息（其他的与功能相关的附加信息）
> 

### 效果演示（可以提供可借鉴的图片）
>

**Comment by tonquer** [comment]
可以加上，你也可以在搜索界面不填关键词搜索，就是全部的

**Comment by tonquer** [comment]
已添加
